Vendicated/Vencord

install.ps1, uninstall.ps1
Installer and Uninstaller for windows (powershell)
=> feat(installer) Windows powershell installer and uninstaller

src/plugins/muteNewGuild.ts
add a plugin that will auto-magically mute newly joined guilds.
=> feat(plugin): add muteNewGuild Plugin

README.md
its silly just like you <:blehhh:1013251244787253258>
pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr pr
=> Add contributing link in readme

src/plugins/randomiseFileNames.ts, src/plugins/randomizeUploads.ts
plugin to randomize uploaded file names
=> feat(plugin): add randomizeUpload

src/plugins/isStaff.ts
=> feat(plugins): Add isStaff plugin

src/plugins/betterUploadButton.ts, src/plugins/randomiseFileNames.ts, src/utils/constants.ts
plugin to upload with a single click and open the context menu with right click
=> feat(plugin): add betterUploadButton

.gitignore, pnpm-lock.yaml, src/plugins/noSystemBadge.ts, src/utils/constants.ts
Remove the tray icon unread icon & taskbar unread count/icon
=> feat: no system badges plugin

src/plugins/noBlockedMessages.ts
Hide all blocked messages from chat
=> feat: no blocked messages plugin

src/plugins/banger.ts, src/plugins/muteNewGuild.ts, src/utils/constants.ts
=> fix(plugins): Fixed BANger

src/plugins/randomiseFileNames.ts
current version doesnt work on web. idk what else to say
=> fix(randomiseFileNames): work correctly on web

CONTRIBUTING.md, README.md, docs/1_INSTALLING.md, docs/2_PLUGINS.md
=> docs docs docs docs

src/plugins/ify.ts
Fix typo and make it a bit more detailed
=> Description change for Spotify Plugin

src/plugins/quickreply.ts
plugin to reply to messages using telegram keybinds (ctrl + direction)
=> feat(plugin): add quickreply

src/ipcMain/index.ts
Allows for plugins to open external urls to apps like spotify and steam
~~idk where to put that array feel free to move it (explode)~~
=> Protocol whitelist

src/plugins/fxTwitter.ts, src/plugins/noCanaryMessageLinks.ts, src/plugins/vxTwitter.ts, src/utils/constants.ts
- **VxTwitter** || Uses VxTwitter to fix embeds from twitter on send
- Added `Dev.Samu` to `src/utils/constants.ts`
=> fxTwitter (plugin)

src/plugins/fart.ts, src/plugins/iLoveSpam.ts, src/utils/constants.ts
=> Fart plugin

package.json, pnpm-lock.yaml, src/api/Commands.ts, src/plugins/echo.ts, src/plugins/fakeClyde.ts
- **FakeClyde** || Uses Clydes message function to send a custom message of your choice (locally)
- **sendBotMessage** || Shortens sending messages via clyde to an api util
=> FakeClyde (plugin) and sendBotMessage (API addition)

src/plugins/fxTwitter.ts
=> Fix fxTwitter regex for issue #97

src/plugins/moreCommands.ts, src/utils/constants.ts
=> added mock command

.gitignore, README.md, docs/2_PLUGINS.md, scripts/build/common.mjs
Allows users to create a `src/userplugins` directory where they can load their own plugins without worrying about git conflicts.
=> feat: gitignored src/userplugins directory

src/plugins/interactionKeybinds.ts
someone complained about it idc
=> fix(interactionKeybinds): disable ping when replying to own message

src/plugins/ify.ts
Improve Spotify premium bypass, turn disable auto pause into an option and add option to keep the activity playing when idling
=> feat(plugin): Ify improvements

src/plugins/banger.ts, src/plugins/banger.tsx
Adds a simple setting to change the video to whatever
=> add(BANger): Added settings to BANger

src/components/PluginSettings/PluginModal.tsx, src/components/PluginSettings/components/SettingBooleanComponent.tsx, src/components/PluginSettings/components/SettingNumericComponent.tsx, src/components/PluginSettings/components/SettingSelectComponent.tsx, src/components/PluginSettings/components/SettingSliderComponent.tsx, src/components/PluginSettings/components/SettingTextComponent.tsx, src/components/PluginSettings/components/index.ts, src/plugins/moyai.ts, src/utils/types.ts, src/webpack/common.tsx
Adds a Slider component type to plugin settings.
Also removes some unsafe destructuring of proxies in other component files.
=> feat: settings sliders

.eslintrc.json, README.md, scripts/build/common.mjs, src/api/Commands/index.ts, src/api/DataStore/LICENSE, src/api/DataStore/index.ts, src/api/index.ts
An alternative to the synchronous Settings API to work around storage limitations of localStorage and allow  storing of arbitrarily large data in form of most Javascript DataTypes,
see https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types
=> Add DataStore (IndexedDB wrapper)

scripts/patcher/install.js, src/api/DataStore/index.ts, src/patchWin32Updater.ts, src/patcher.ts
This is fully untested because I don't have a Windows PC, so please test if everything works correctly
=> Windows: Patch host updater to reinject

src/components/PluginSettings/index.tsx, src/components/PluginSettings/styles.ts
use switch in plugin settings, 
this pr is probably not perfect
submit feedback/corrections thx
=> feat: switch in plugin settings

src/plugins/fxTwitter.ts, src/plugins/moreCommands.ts, src/plugins/noCanaryMessageLinks.ts
=> Update license headers in files created by Samu

src/plugins/showHiddenChannels.tsx
- Show last message date
- Don't send messages API request
- Fix collapsing categories containing only hidden channels
(thx @CanadaHonk for the help)
=> [ShowHiddenChannels] Add last message info, fix collapsing

src/plugins/showHiddenChannels.tsx, src/plugins/vcDoubleClick.ts, src/utils/constants.ts
- Fixes plugin for newer Discord
- Adds support for stage channels
=> Fix vcDoubleClick, add support for stage channels

src/plugins/vcDoubleClick.ts
Fixup for #159
Sorry, I forgot that while refactoring and did not test again
=> fix(vcDoubleClick): add required parentheses

package.json, pnpm-lock.yaml, scripts/build/build.mjs, scripts/build/buildWeb.mjs, src/components/PluginSettings/index.tsx, src/globals.d.ts, src/utils/logger.ts, src/webpack/patchWebpack.ts
=> Patcher: More useful errors with code diffs

src/plugins/showHiddenChannels.tsx
so many pull requests for one plugin 🥇
=> fix(showHiddenChannel): rightclick fix + modal button text

src/Vencord.ts, src/api/Commands/commandHelpers.ts, src/components/PluginSettings/PluginModal.tsx, src/components/PluginSettings/index.tsx, src/plugins/experiments.tsx, src/plugins/ignoreActivities.ts, src/plugins/index.ts, src/plugins/interactionKeybinds.ts, src/plugins/petpet.ts, src/plugins/pronoundb/components/PronounsChatComponent.tsx, src/plugins/reverseImageSearch.tsx, src/plugins/sendify.ts, src/utils/logger.ts, src/webpack/common.tsx, src/webpack/patchWebpack.ts, src/webpack/webpack.ts
Makes unsuccessful webpack searches
- throw if IS_DEV
- log warning if !IS_DEV
Additionally, if IS_DEV, logs a warning if patches have not been applied. This warning will likely always be printed due to lazily loaded modules being patched later, but imo it's still useful
=> Webpack Warnings & Errors

README.md, src/patcher.ts
=> fix renamed app.asar detection on Windows

package.json, pnpm-lock.yaml, src/components/CheckedTextInput.tsx, src/components/PatchHelper.tsx, src/components/PluginSettings/PluginModal.tsx, src/components/PluginSettings/components/SettingTextComponent.tsx, src/components/PluginSettings/index.tsx, src/components/index.ts, src/plugins/settings.ts, src/webpack/common.tsx
=> PatchHelper, a tool to help you write patches

src/components/ErrorBoundary.tsx, src/components/Flex.tsx, src/plugins/reverseImageSearch.tsx, src/plugins/spotifyControls/PlayerComponent.tsx, src/plugins/spotifyControls/SpotifyStore.ts, src/plugins/spotifyControls/index.tsx, src/plugins/spotifyControls/styles.css, src/utils/misc.tsx, src/utils/proxyLazy.ts, src/webpack/common.tsx
=> SpotifyControls plugin

src/plugins/spotifyControls/PlayerComponent.tsx
=> fix(spotifyControls): add album/cover null checks (local files)

src/plugins/moyai.ts
=> feat(plugins): add vc effect event to moyai plugin

src/plugins/lastfm.ts, src/plugins/lastfm.tsx, src/utils/constants.ts
adds a plugin for last.fm rpc, based on [dimdenGD/LastFMRichPresence](https://github.com/dimdenGD/LastFMRichPresence)
=> feat(plugin): Last.fm rich presence

src/plugins/arRPC.tsx, src/utils/constants.ts
You love [arRPC](https://github.com/OpenAsar/arrpc)!
=> feat(plugin): WebRichPresence (arRPC)

src/plugins/noUnblockToJump.ts, src/plugins/yesBlockedMessages.ts
removes the following sort of prompt and lets you jump to the message without unblocking a person:
(i.e. in replies, search results and message urls)
=> feat(plugin): NoUnblockToJump

src/plugins/fakeNitro.ts
also renames emojis to emotes (closes #204)
=> feat(fakeNitro): add an option to change emote sizes

src/plugins/oneko.ts, src/plugins/platformIndicators.tsx, src/webpack/common.tsx
adds platform icons to users list in servers and DMs and optionally user badges
=> feat(plugin): PlatformIndicators

src/plugins/arRPC.tsx
final final PR (until 3.0 at least :wink:)
=> fix(arRPC): fix error on null activity

src/plugins/dictionary.ts, src/plugins/quickMention.tsx, src/utils/constants.ts
A plugin that let you search for words' definitions (from Urban Dictionary) without leaving Discord.
=> feat(plugin): Urban Dictionary 

src/plugins/messageTags.ts, src/utils/constants.ts
Commands:
`/tags create` - create a new tag
`/tags list` - list all tags
`/tags delete` - delete a tag
`/tags preview` - preview a tag
`/<tag>` - makes you explode
=> feat(messageTags): Add message quick reply plugin

src/plugins/loadingQuotes.ts
you've seen them in the dms ven :)))))
=> add new quotes to loadingQuotes

scripts/patcher/common.js
Support for DVM installation path (`~/.dvm`)
=> Add support for DVM installation path.

src/plugins/serverListIndicators.tsx, src/webpack/common.tsx
Adds a little indicator on the server list for online friends and/or server count
=> feat(plugin): add ServerListIndicators

src/plugins/memberCount.tsx, src/utils/constants.ts
=> add me to contributors

src/plugins/reverseImageSearch.tsx
the old url is gon 🙁
this the best we got
=> google changed their shit

src/plugins/shikiCodeblocks/components/Highlighter.tsx, src/plugins/shikiCodeblocks/hooks/useShikiSettings.ts, src/plugins/shikiCodeblocks/style.css
=> fix(ShikiCodeblocks): spoilers

src/api/Commands/commandHelpers.ts, src/plugins/showHiddenChannels.tsx, src/webpack/common.tsx
Looks like they removed `lastActiveTimestamp`
=> [ShowHiddenChannels] Fix last message date

.github/workflows/build.yml, README.md
First attempt, probably doesn't work. Have fun fixing it <3
Thanks,
Elliott
=> Also push builds to https://github.com/Vencord/builds

src/utils/constants.ts
=> pointy is a "contributor"

src/plugins/reverseImageSearch.tsx
=> Add ImgOps to ReverseImageSearch

src/plugins/ignoreActivities.tsx
Only merge this PR when Discord pushes the update to stable
=> fix(IgnoreActivities): Fix for upcoming change

src/ipcMain/index.ts, src/patchWin32Updater.ts, src/preload.ts, src/utils/IpcEvents.ts
Migrates the Windows update patcher to the electron 17+ method
Untested, testing this is painful
=> Update Windows Update patcher

README.md
normal users will stop asking dumb questions in support!! pog
=> remove power user instructions from readme

src/plugins/apiMessagePopover.ts
Works in both current stable and canary
=> Fix Message Popover API

src/plugins/volumeBooster.ts
=> Future proof Volume Booster to work with volume settings syncing

src/Vencord.ts, src/api/settings.ts, src/components/VencordSettings/Updater.tsx, src/components/VencordSettings/VencordTab.tsx, src/patcher.ts, src/utils/updater.ts
=> Make Windows Ctrl+Q feature optional; add opt-in auto update

src/plugins/typingTweaks.tsx
Probably fixes other languages too, idk. I also made it use nicknames in guilds
=> fix(TypingTweaks): fix crash when using UK English

src/plugins/messageLinkEmbeds.tsx
=> MessageLinkEmbeds: Prevent infinite cycles

src/plugins/invisibleChat/components/DecryptionModal.tsx, src/plugins/invisibleChat/index.tsx
=> Feat(InvisibleChat): Add Autodecryption

src/webpack/common/components.ts, src/webpack/common/types/components.d.ts
Tooltip component no longer contains `Positions`
=> fix tooltip component check

src/webpack/common/components.ts, src/webpack/common/types/components.d.ts
Exposes a searchable select component.
=> feat: SearchableSelect

src/api/settings.ts, src/components/handleComponentFailed.ts, src/plugins/crashHandler.ts, src/plugins/noF1.ts, src/plugins/noRPC.ts, src/utils/modal.tsx, src/utils/types.ts, src/utils/updater.ts
=> feat: Crash Handler

src/components/PatchHelper.tsx, src/components/PluginSettings/index.tsx, src/components/VencordSettings/BackupRestoreTab.tsx, src/components/VencordSettings/ThemesTab.tsx, src/components/VencordSettings/Updater.tsx, src/components/VencordSettings/index.tsx, src/components/VencordSettings/settingsStyles.css, src/plugins/apiBadges.tsx, src/plugins/emoteCloner.tsx, src/plugins/typingTweaks.tsx, src/plugins/vcNarrator.tsx, src/plugins/viewRaw.tsx, src/webpack/common/components.ts, src/webpack/common/types/components.d.ts
=> Fix for latest Discord Update

docs/1_INSTALLING.md
=> Rename from sudo to root

src/api/Notifications/NotificationComponent.tsx, src/api/Notifications/Notifications.tsx, src/api/Notifications/styles.css
Also doesn't depend on FormTitles anymore
=> Notifications: Permanent option and close button

src/plugins/silentTyping.tsx
Same as #566 for SilentTyping
Maybe we should implement a chat bar icon API?
=> fix(silentTyping): fix chatbar icon patch

src/plugins/apiNotices.ts, src/plugins/crashHandler.ts, src/plugins/disableDMCallIdle.ts, src/plugins/experiments.tsx, src/plugins/fakeNitro.ts, src/plugins/ignoreActivities.tsx, src/plugins/moyai.ts, src/plugins/noScreensharePreview.ts, src/plugins/pronoundb/index.ts, src/plugins/revealAllSpoilers.ts, src/plugins/showHiddenChannels/index.tsx, src/plugins/spotifyCrack.ts, src/plugins/typingIndicator.tsx, src/plugins/volumeBooster.ts, src/plugins/whoReacted.tsx
=> Improvements for patches and misc stuff

src/api/ContextMenu.ts, src/api/index.ts, src/plugins/apiContextMenu.ts, src/webpack/patchWebpack.ts, src/webpack/webpack.ts
You can see it being used here https://github.com/Nuckyz/Vencord/blob/feat/permissions-viewer-context-menu-api/src/plugins/permissionsViewer/index.tsx
=> feat: Context Menu API

src/plugins/roleColorEverywhere.tsx
Seems Discord are now using a full channel object here. Patch changed to accomodate.
=> fix(RoleColorEverywhere): chat mentions

src/plugins/messageLogger/index.tsx
=> messageLogger: fix edited timestamp styling & add i18n

src/plugins/uwuify.ts
Algorithm ported from `uwuify` rust crate, which works well
=> feat(uwuify): impwowove uwuification awgowithm :3

package.json, pnpm-lock.yaml, scripts/build/buildWeb.mjs, scripts/build/common.mjs, src/Vencord.ts, src/api/Notifications/NotificationComponent.tsx, src/api/Notifications/Notifications.tsx, src/api/Notifications/notificationLog.tsx, src/api/Notifications/styles.css, src/api/settings.ts, src/components/VencordSettings/VencordTab.tsx, src/plugins/crashHandler.ts, src/plugins/devCompanion.dev.tsx, src/webpack/common/react.ts
https://user-images.githubusercontent.com/45497981/229183035-9c701331-f4f9-41f1-b6d4-6203d9d5fbcc.mp4
=> Add Notification log

src/plugins/betterFolders/betterFolders.css, src/plugins/readAllNotificationsButton.tsx
=> Fix things being display twice with BetterFolders

.github/workflows/reportBrokenPlugins.yml, scripts/build/buildWeb.mjs, src/components/PluginSettings/index.tsx, src/plugins/consoleShortcuts.ts, src/plugins/devCompanion.dev.tsx, src/plugins/gameActivityToggle/index.tsx, src/plugins/gameActivityToggle/style.css
[Fix report broken patches for canary](https://github.com/Vendicated/Vencord/commit/4b014fdbef6d9e721899bede2a01830399dcb4b6)
[Unexplode Discord Web](https://github.com/Vendicated/Vencord/commit/e957f38fb21253cc6e24af019dc9c2b8a95968f5)
[Fix hardcoded class name](https://github.com/Vendicated/Vencord/commit/9544dad7d0dae66c424f8c76b5f1f6e2c2fa2f0e)
[Add findStore shortcut](https://github.com/Vendicated/Vencord/commit/33d3764da5f554fe9f47cffd41dc57387f9a8e8f)
[Make Game Activity Toggle use proper classes](https://github.com/Vendicated/Vencord/commit/06c0766181c4475d7eeff589aa06ec5585d0310d)
=> Misc fixes (read desc)

src/plugins/spotifyControls/spotifyStyles.css
add some transitions guh it looks so scuffed
=> SpotifyControls: add album art hover transition

src/plugins/friendInvites.ts, src/utils/constants.ts
Hacky way to fix friend invites may break in the future
=> Fix FriendInvites

src/plugins/betterFolders/index.ts, src/utils/constants.ts
me on my way to fix random small stuff lol
=> BetterFolders: Fix Close all not working

src/api/settings.ts, src/components/VencordSettings/VencordTab.tsx, src/main/patcher.ts
=> feat(setting): Disable minimum window size #834

src/plugins/noReplyMention.tsx, src/plugins/quickReply.ts, src/utils/constants.ts
=> feat(NoAutoReplyMention): Inverse shift reply behaviour

src/plugins/userVoiceShow/index.tsx
There was no margin bottom and it glued directly to the border.
After:
=> VoiceUserShow: Fix lack of bottom margin

src/plugins/spotifyControls/index.tsx
- SpotifyControls: Fixed flashing button row when hovering profile panel while `Show Controls On Hover` option is enabled
=> SpotifyControls: Fixed flashing button row

src/plugins/pronoundb/pronoundbUtils.ts
When I used useAwaiter, it gave me some idea how it worked and therefore why this bug occurs.
It worries me how quick i did this :p
=> PronounDB: Fix pronouns flickering

src/plugins/welcomeStickerPicker.tsx, src/webpack/common/types/menu.d.ts
=> GreetStickerPicker: greet with stickers of your choice

src/plugins/shikiCodeblocks/shiki.css
=> Shiki: Make CodeBlock button texts not copyable

src/plugins/disableDMCallIdle.ts
Merge this when the new code reaches stable
=> Revert "Delete DisableDMCallIdle: Discord removed this 'feature'"

src/plugins/reviewDB/Utils/ReviewDBAPI.ts, src/plugins/reviewDB/Utils/Utils.tsx, src/plugins/reviewDB/components/MessageButton.tsx, src/plugins/reviewDB/components/ReviewBadge.tsx, src/plugins/reviewDB/components/ReviewComponent.tsx, src/plugins/reviewDB/components/ReviewsView.tsx, src/plugins/reviewDB/entities/Badge.ts, src/plugins/reviewDB/entities/Review.ts, src/plugins/reviewDB/index.tsx
ven will stop being angry and merge
=> add reviewdb bacc

src/plugins/showMeYourName/index.tsx, src/plugins/showMeYourName/styles.css
Controls how nicknames are displayed: nick + user, user + nick or user only
Closes #336
=> feat(plugin): ShowMeYourName

src/plugins/gifPaste.ts, src/plugins/invisibleChat/components/EncryptionModal.tsx, src/plugins/quickMention.tsx, src/plugins/sendTimestamps.tsx, src/plugins/sendTimestamps/index.tsx, src/plugins/sendTimestamps/styles.css, src/utils/constants.ts, src/utils/discord.ts, src/webpack/common/utils.ts
(ignore the horrid ui)
https://user-images.githubusercontent.com/45497981/231939468-71d17803-2d7a-40b3-a6b9-673ec8d5eda8.mp4
=> SendTimestamps

src/plugins/showMeYourName/index.tsx
settings were reversed (the diff is wild, i just changed the predicates)
=> fix(smyn): reversed settings

browser/manifest.json, browser/modifyResponseHeaders.json
Makes Vencord work with [Discord PWA](https://github.com/NeverDecaf/discord-PWA)
=> Make Vencord Extension run in iframes

src/api/Commands/index.ts, src/plugins/messageTags.ts
Fixed so it doesn't always make a second reply with "Invalid sub-command"
=> messageTags: Fix duplicate entries & replies

src/plugins/silentTyping.tsx
*Silent Typing Tooltip Silently driving me insane.*
=> SilentTyping: Make Tooltip text casing consistent w other plugins

.github/workflows/build.yml, .github/workflows/publish.yml, browser/background.js, browser/manifestv2.json, package.json, scripts/build/buildWeb.mjs
This code just doesn't work and i don't know why
=> firefox: Fix csp (QuickCss, themes, some plugins)

src/plugins/invisibleChat/index.tsx, src/plugins/sendTimestamps/styles.css, src/plugins/silentMessageToggle.tsx, src/plugins/silentTyping.tsx
=> Make chat bar buttons have a consistent size

src/plugins/whoReacted.tsx, src/utils/constants.ts
Solves the [following issue](https://github.com/Vendicated/Vencord/issues/868)
Have linted and tested on Discord Canary, has no more issues.
=> WhoReacted: Fix clicking user pfps also adding reaction

src/components/PluginSettings/PluginModal.tsx
=> Plugin Settings: Better margin for plugin settings modal

src/api/MessageEvents.ts, src/plugins/apiMessageEvents.ts, src/plugins/fakeNitro.tsx, src/plugins/typingIndicator.tsx
=> Fix FakeNitro Stickers

src/plugins/textReplace.tsx
Passing in the force updater seems hacky and may be slightly broken :woman_shrugging:
=> TextReplace: Test rules section

src/plugins/usrbg/index.css, src/plugins/usrbg/index.tsx
without massive css of course :3
=> USRBG: Add VoiceBackground

src/components/Icons.tsx, src/plugins/showConnections/VerifiedIcon.tsx, src/plugins/showConnections/index.tsx, src/plugins/showConnections/styles.css, src/webpack/common/components.ts, src/webpack/common/types/components.d.ts
Not sure if Copy/Link icon would look better in front of the text instead of after
https://github.com/Vendicated/Vencord/assets/45497981/9b0d72ba-2386-4c65-a6af-ab7a2bc9c9eb
=> ShowConnections: Add verified & copy/link icons in tooltip

.eslintrc.json, src/components/PluginSettings/PluginModal.tsx, src/plugins/invisibleChat/index.tsx, src/plugins/sendTimestamps/styles.css, src/plugins/silentMessageToggle.tsx, src/plugins/silentTyping.tsx, src/plugins/translate/TranslateIcon.tsx, src/plugins/translate/TranslateModal.tsx, src/plugins/translate/TranslationAccessory.tsx, src/plugins/translate/index.tsx, src/plugins/translate/languages.ts, src/plugins/translate/settings.ts, src/plugins/translate/styles.css, src/plugins/translate/utils.ts, src/utils/types.ts
https://github.com/Vendicated/Vencord/assets/45497981/73792267-1382-4bba-a7d2-8a59193b05d9
=> New Plugin: Translate

src/plugins/experiments.tsx
=> experiments: Add a warning card to experiments page

src/plugins/emoteCloner.tsx
~~Should probably rename the plugin. But to what?~~
=> EmoteCloner: Add Sticker cloning

src/plugins/emoteCloner.tsx
=> emoteCloner: allow other characters in sticker names

src/plugins/vcNarrator.tsx
if anyone wishes to hear their own name on join this should work
=> VcNarrator: Add 'Narrate Self' option

src/plugins/invisibleChat/index.tsx
=> feat(InvisibleChat): use discords embed api

src/plugins/urbanDictionary.ts
=> Urban Dictionary: better embed

src/plugins/permissionsViewer/index.tsx, src/plugins/permissionsViewer/utils.ts, src/plugins/showHiddenChannels/components/HiddenChannelLockScreen.tsx, src/plugins/showHiddenChannels/index.tsx
Merge when broken SHC patches reach stable
=> Fix SHC broken patches; Sort PermViewer channel overwrites roles

src/plugins/fakeNitro.ts, src/plugins/fakeNitro.tsx
=> FakeNitro: Fix unavailable emotes; Discord Stickers are now free

src/plugins/messageClickActions.ts
makes backspace delete message logger's history of a deleted message too
=> feat(MessageClickAction): delete message logger history

src/plugins/reviewDB/index.tsx, src/plugins/reviewDB/utils.tsx
2 line fix
discord decided to make oauth2 response a object instead of just URL
=> fix reviewdb auth

src/plugins/settings.tsx
examples
```js
Vencord.Plugins.plugins.Settings.customSections.push((ID) => ({
section: "guhhh",
label: "Guh",
element: () => "Ven explosion soon"
}))
```
```js
Vencord.Plugins.plugins.Settings.customSections.push(ID => ({ section: ID.DIVIDER }))
```
=> Settings: add custom sections support

src/plugins/uwuify.ts
=> Improve uwuify

src/plugins/invisibleChat/index.tsx
=> InvisibleChat: fix indicator & crashes

src/plugins/viewIcons.tsx
=> ViewIcons: Fix animated server pfps & profile edit button

src/utils/settingsSync.ts
this might help more than deflate tbh
=> perf(cloud sync): minify synced settings

src/plugins/relationshipNotifier/functions.ts, src/plugins/relationshipNotifier/types.ts, src/plugins/relationshipNotifier/utils.ts
=> fix(RelationshipNotifier): Ignore user-actioned friend requests

src/components/PluginSettings/index.tsx
First contribution, resolves #323 
Adds a very simple "Show New" option in plugin settings that will show plugins with the "New" badge.
=> Add "Show New" option in plugin settings

src/plugins/disableDMCallIdle.ts
minor change, its 3 minutes now
=> [chore] Update DisableDMCallIdle description

src/plugins/callTimer.tsx, src/plugins/voiceMessages/DesktopRecorder.tsx, src/plugins/voiceMessages/VoicePreview.tsx, src/plugins/voiceMessages/WebRecorder.tsx, src/plugins/voiceMessages/index.tsx, src/plugins/voiceMessages/settings.ts, src/plugins/voiceMessages/styles.css, src/plugins/voiceMessages/utils.ts, src/utils/react.tsx
Adds waveforms and VoiceRecording preview component
=> VoiceMessages UI

src/plugins/memberCount.tsx
Fixes #1453
That was surprisingly easy
=> MemberCount: fix family center crash

src/plugins/voiceMessages/index.tsx
Add a reply function to the voice message plugin.
=> VoiceMessages: Support replies

src/plugins/muteNewGuild.tsx
Mute server when joining in preview mode
=> MuteNewGuild: Support lurked guilds

src/plugins/textReplace.tsx
people somehow managed to delete the last row lol
=> textReplace: fix edge case

src/components/PluginSettings/PluginModal.tsx
=> add bottom margin to settings section

src/plugins/reviewDB/components/ReviewsView.tsx, src/plugins/reviewDB/settings.tsx
=> [ReviewDB] hide blocked users

src/plugins/sendTimestamps/index.tsx, src/plugins/translate/TranslateIcon.tsx
I belive this should make it easier to edit the buttons in a theme by adding an actual aria-label
=> Translate/SendTimestamps: Fix accessibility

src/plugins/messageLogger/index.tsx
=> messageLogger: fix ignore guild

src/plugins/showMeYourName/index.tsx
=> ShowMeYourName: Option to use display names instead of usernames

src/plugins/invisibleChat/components/EncryptionModal.tsx
This will allow non-letters to be used in covers :3
=> feat(InvisibleChat) Improve Encryption validity

src/main/patchWin32Updater.ts
This is more generic rewrite allowing for more paths to be added in the future for whatever reason (like a rename in future Discord versions).
(The "OpenAsar" code previously was completely wrong lol!)
=> Fix patching Win32 updater with OpenAsar

src/plugins/copyUserURLs.tsx, src/utils/constants.ts
this adds a button to copy user urls, if this is useless just close, I mainly made it for myself since I use user urls a lot
=> feat: add copyUserURLs plugin

src/plugins/gameActivityToggle/index.tsx, src/utils/constants.ts
=> gameActivityToggle: Fix disabled SVG look

src/plugins/messageLinkEmbeds.tsx
I should probably stop doing commits on main
=> messageLinkEmbeds: fix AutoModEmbed on compact mode

src/plugins/themeAttributes/README.md, src/plugins/themeAttributes/index.ts
Please see https://github.com/Vendicated/Vencord/blob/themeAttrs/src/plugins/themeAttributes/README.md for a description
if there are any other elements inside discord where you could use such data attributes, please comment
provide as much detail as possible:
- What element specifically?
- What attributes do you want?
- What's your use case? What are you trying to do?
do not suggest elements where you can already achieve the same by matching some child using `:has`
do not request demangled classes (classes without the `-ajsjakjs` suffix)
=> new plugin: themeAttributes

src/plugins/messageLogger/index.tsx
The two guys added this feature didn't check edited message 💀 #1275 #1420
=> MessageLogger: fix ignore by id doesn't ignore edited

src/plugins/messageLogger/index.tsx
lmk if it should have a toggle, but i think it shouldnt
=> messageLogger: make ignoreChannels also ignore threads

src/plugins/hideAttachments.tsx
=> HideAttachments: fix broken css

src/plugins/loadingQuotes.ts
i consider this a significant improvement to Vencord
=> LoadingQuotes: add a new quote

src/components/PluginSettings/ContributorModal.tsx, src/components/PluginSettings/PluginModal.tsx, src/components/PluginSettings/contributorModal.css, src/components/PluginSettings/index.tsx, src/components/PluginSettings/userPopoutHideBotTag.css, src/components/VencordSettings/addonCard.css, src/plugins/pronoundb/pronoundbUtils.ts, src/plugins/showConnections/index.tsx, src/utils/discord.tsx, src/webpack/common/stores.ts, src/webpack/common/types/components.d.ts
github and website are obtained from discord connections
https://github.com/Vendicated/Vencord/assets/45497981/3fc212ec-18ca-48c1-a0d2-588852d53285
=> add custom plugin author popouts

src/plugins/pictureInPicture.tsx, src/plugins/previewMessage.tsx, src/utils/constants.ts
This plugin adds a picture in picture button for videos next to the Download button.
TODO:
- ~~Make the SVG fit more with the others color-wise~~
- ~~Find a way to remove the ts-ignore in the onClick event~~
- ~~Make the hover tooltip work~~
- ~~Test more?~~
I think most of the essential stuff is done
=> feat(plugin): PictureInPicture

src/plugins/dearrow/README.md, src/plugins/dearrow/index.tsx, src/plugins/dearrow/styles.css
Makes YouTube embed titles and thumbnails less sensationalist, powered by [Dearrow](https://dearrow.ajay.app/)
=> New Plugin: Dearrow

src/plugins/pictureInPicture.tsx
=> pictureInPicture: don't show PiP button on normal file

src/plugins/serverProfile/GuildProfileModal.tsx
This fixes a crash when using the plugin on a lurked guild.
=> serverProfile: fix crash with lurked guilds

src/plugins/reviewDB/components/ReviewComponent.tsx, src/webpack/common/classes.ts
fix the ugly square box behind image when viewIcons
fix the bot tag "system" in reviewdb warning
=> fix modal image + reviewdb bot tag

src/plugins/permissionFreeWill/README.md, src/plugins/permissionFreeWill/index.ts
aka FreiheitlicheBerechtigungsKonfiguration
=> feat(plugin): PermissionFreeWill

src/plugins/whoReacted/README.md, src/plugins/whoReacted/index.tsx
"Fix"
(the code is probably somehow worse)
=> Fix WhoReacted

src/main/index.ts
Makes header patching case-independent.
=> fix: Content Security Policy patching

src/plugins/vcNarrator/index.tsx
`{{NICKNAME}}` is placeholder for user's `guild_member.nick` object if it exists, otherwise it defaults to `username`.
Hopefully it should compile first try
=> feat(VcNarrator): add `{{NICKNAME}}` as placeholder

src/plugins/fakeNitro/index.ts
=> FakeNitro: Add app icon customization

src/plugins/onePingPerDM/index.ts
- Select option for DM to effect
- Toggle for allowing mentions
- Toggle for allowing @ everyone and @ here for group dms
=> onePingPerDM: add settings

src/plugins/customRPC/index.tsx
got kinda lucky in that not alot broke with CustomRPC
=> Fix CustomRPC

src/plugins/fakeProfileThemes/index.tsx
Store patch has same issue as typing indicator I think
=> fix: fakeProfileThemes

src/plugins/sortFriendRequests/index.tsx
Fixes the patches for sortFriendRequests
=> fix: sortFriendRequests patches

src/plugins/onePingPerDM/index.ts
=> fix: onePingPerDM

src/plugins/forceOwnerCrown/index.ts
Also resolves #1830 as it returns the original `isOwner` by default now
=> forceOwnerCrown: fix

src/plugins/showAllMessageButtons/index.ts
not sure why this was such an insane regex in the first place, this works just fine for me
=> fix: ShowAllMessageButtons

src/plugins/serverProfile/GuildProfileModal.tsx
This fixes the Friends/Blocked Users tabs being blank
=> fix: ServerProfile

src/plugins/typingIndicator/index.tsx, src/plugins/typingTweaks/index.tsx, src/utils/discord.tsx
I'm not sure where the best place for "TYPING_TEXT_STYLE" is. I thought it was cleaner not to write it in a patch.
=> TypingTweaks: fix

src/plugins/noUnblockToJump/index.ts
=> Fix: noUnblockToJump

scripts/generateReport.ts, src/api/ContextMenu.ts, src/components/VencordSettings/UpdaterTab.tsx, src/plugins/customRPC/index.tsx, src/plugins/spotifyControls/spotifyStyles.css, src/utils/types.ts, src/webpack/patchWebpack.ts
This PR fix the typo in multiple files.
```pseudo
occured > occurred
Wheter > Whether
sucessfully > successfully
occured > occurred
Deverloper > Developer
cusotm > custom
irrelavent > irrelevent
existant > existent
```
=> fix: typo in multiple files

src/main/updater/git.ts
This is untested as i would have to wait for the commit to be pushed there but should work
=> Fix git updater for dev branch

src/plugins/pictureInPicture/index.tsx
imagine making your custom component override discord's
couldn't be me
=> fix: PiP replacing video download button

src/plugins/pictureInPicture/index.tsx
redo #1725 and #1775 because lumap ate them
=> PiP: fix issues / styles

src/plugins/imageZoom/index.tsx, src/plugins/imageZoom/styles.css
=> imageZoom: dont close carousel modal on image click

src/plugins/betterFolders/index.tsx, src/plugins/emoteCloner/index.tsx
=> EmoteCloner: make the error toasts useful

src/plugins/gifPaste/index.ts
meow
fixes https://github.com/Vendicated/Vencord/issues/1045
=> gifPaste: fix unable to use gif picker in profile customization

src/plugins/fakeNitro/index.ts
yes an one-character-change pull request
=> fakeNitro: disallow emoji in add reaction

src/plugins/customRPC/index.tsx
=> customRpc: fix discord attachment link

src/plugins/messageTags/index.ts
=> fix(channeltags): message author should be clyde (#644)

src/webpack/common/utils.ts
Fixes the thing everyone is posting about in #632
=> fix hljs find

src/plugins/oneko/index.ts
Script now uses requestAnimationFrame
=> oneko: update script version

src/utils/types.ts, src/webpack/patchWebpack.ts
draft, would like input on if throwing and handling in the catch is the right thing to do
=> feat(patcher): Grouped replacements

src/api/Commands/commandHelpers.ts
=> fix createBotMessage

src/plugins/oneko/index.ts
=> oneko: allow oneko in reduced motion

src/plugins/alwaysAnimate/index.ts
Basically makes the guild banner always animate, even when not hovered over
=> AlwaysAnimate: Add guild banner

src/plugins/reviewDB/auth.tsx, src/plugins/reviewDB/components/ReviewComponent.tsx, src/plugins/reviewDB/components/ReviewsView.tsx, src/plugins/reviewDB/index.tsx, src/plugins/reviewDB/reviewDbApi.ts, src/plugins/reviewDB/settings.tsx, src/plugins/reviewDB/style.css, src/plugins/reviewDB/utils.tsx
cant bother to write description go read code :trollface:
=> [ReviewDB] update for new api changes; some fixes

src/plugins/readAllNotificationsButton/index.tsx
how did nobody say anything about this in over a year
=> readAllNotificationsButton: also mark voice channels as read

src/plugins/fakeNitro/index.ts, src/plugins/fixYoutubeEmbeds.desktop/native.ts
=> FakeNitro: Send fake links using Discord hyperlink markdown feature

src/plugins/imageZoom/components/Magnifier.tsx, src/plugins/imageZoom/index.tsx
=> Fix image zoom

src/plugins/whoReacted/index.tsx, src/utils/constants.ts
it didn't break anything
I *did* put myself in `src/utils/constants.ts` (and not the `whoReacted` plugin contributors) but feel free to remove me from it if this contribution is too small.
=> whoReacted: fix reaction count being off by one

browser/GMPolyfill.js, src/components/VencordSettings/CloudTab.tsx, src/utils/cloud.tsx, src/utils/settingsSync.ts
See: https://discord.com/channels/1015060230222131221/1026515880080842772/1212203561786802217
=> fix Vencloud not working on UserScript

src/plugins/_core/settings.tsx, src/plugins/betterSettings/README.md, src/plugins/betterSettings/index.tsx, src/webpack/common/components.ts, src/webpack/common/types/components.d.ts
Makes your settings-menu-opening experience more pleasant by removing unnecessary delays and organizing the right-click menu.
Also cleans up a hack related to the right click menu in the core settings plugin.
=> new plugin: BetterSettings ~ improves Discord's settings

src/plugins/emoteCloner/index.tsx
discord.com doesnt work with gif sticker (404)
=> emoteCloner: fix clone gif sticker

src/plugins/betterSettings/index.tsx
Loads the settings TOC instantly rather than on hover now. Easier that way.
=> fix(BetterMenu): Fix patches

src/components/PluginSettings/index.tsx
=> plugin settings: fix filter dropdown having no padding

scripts/generateReport.ts, src/components/VencordSettings/PatchHelperTab.tsx, src/plugins/index.ts, src/plugins/resurrectHome/index.tsx, src/utils/types.ts, src/webpack/patchWebpack.ts
Adds a button to view the Server Home in the Server Guide channel row. Also adds support for array finds because it was needed to match the right module.
=> Array support for find + ResurrectHome: View Server Home Button on Server Guide

src/plugins/validUser/index.tsx
Change patch from 50 to 100 chars to match
```js
function(e,t,n){"use strict";n.r(t);var i=n("735250");n("470079");var r=n("239091"),s=n("644956"),a=n("819366"),o=n("592125");t.default={handleUserContextMenu(e,t,s,a){let l=o.default.getChannel(t);null!=l&&(0,r.openContextMenuLazy)(a,async()=>{let{default:t}=await Promise.all([n.e("99387"),n.e("79695"),n.e("1502"),n.e("70866"),n.e("12435"),n.e("6696")]).then(n.bind(n,"757387"));return n=>(0,i.jsx)(t,{...n,user:e,channel:l,guildId:s})})},react(e,t,n){let{userId:r,channelId:o,parsedUserId:l,roleId:u,roleName:d}=e;return null==r&&(null!=u||"@everyone"===d||"@here"===d)?(0,i.jsx)(s.default,{inlinePreview:n.formatInline,...e,children:t(e.content,n)},n.key):(0,i.jsx)(a.default,{className:"mention",userId:r,channelId:o,parsedUserId:l,inlinePreview …
```
=> fix ValidUser

src/plugins/implicitRelationships/index.ts, src/plugins/sortFriendRequests/index.tsx
=> fix sort conflict of ImplicitRelationships & SortFriendRequests

src/plugins/messageClickActions/index.ts
=> MsgClickActions: control ping via shift & NoReplyMention plugin

src/plugins/reviewDB/index.tsx
Fixes reviewdb context menus being added to folders (315f4f4)
=> fix(reviewdb): folder context menus

src/plugins/permissionsViewer/components/RolesAndUsersPermissions.tsx
=> permissionsViewer: add role & user context menus to copy id

src/plugins/silentTyping/index.tsx, src/utils/constants.ts
=> SilentTyping: add chat input context menu option to toggle

src/components/VencordSettings/AddonCard.tsx, src/components/VencordSettings/addonCard.css, src/utils/constants.ts
Fix text overflow for long titles in the plugin list
=> Plugin Settings: fix text overflow for long plugin names

src/plugins/translate/TranslateIcon.tsx, src/plugins/translate/settings.ts
Felt bad for pining Vee to add this so I did it myself.
=> feat(Translate): add toggle for chat bar icon

src/plugins/xsOverlay.desktop/index.ts
(it was far too long, and not functional because you cant enter decimals into number optiontype :finnadie:)
(why is this an emote on github lmaoooo)
=> XSOverlay: Adjust message length timeout

src/plugins/emoteCloner/index.tsx, src/utils/constants.ts
Small patch that allows cloning an emoji from a message reaction. 
Would solve this request: Vencord/plugin-requests#179
=> EmoteCloner: allow cloning from reactions

src/plugins/fakeNitro/index.tsx
Patches FakeNitro to allow posting subscription-locked emojis, *hopefully* shouldn't cause issues 🙏
=> FakeNitro: allow using subscription-locked emojis

src/plugins/moreUserTags/index.tsx
added a trial mod tag because some servers only allow new mods to timeout members
=> MoreUserTags: Add chat moderator tag

src/plugins/readAllNotificationsButton/index.tsx
title
Fixes #1835 
Reopened to be editable
=> fix(readAllNotificationsButton) fix #1835 (now reading threads)

src/plugins/replaceGoogleSearch/index.tsx
=> fix(replaceGoogleSearch): correct GitHub casing

src/plugins/quickReply/index.ts
=> QuickReply: skip blocked messages if NoBlockedMessages enabled

src/plugins/appleMusic.desktop/index.tsx
Adds an option to disable the large/small image.
=> AppleMusicRichPresence: add option to disable large/small image

src/plugins/betterRoleDot/index.ts
some people still like it despite having betterRoleContext
=> betterRoleDot: fix click to copy role color in profile

src/components/PluginSettings/index.tsx, src/components/PluginSettings/styles.css
yellow is gone so ig just do it with css
the button in title:
=> ui(RestartCard): fix yellow button now being blue

src/plugins/showConnections/index.tsx
fixes showconnections for simplified profiles
fixing reviewdb and permviewer is as easy as this but im kinda stupid and couldnt figure out how to make scrolling work 😭
=> fix showconnections in new profiles

src/plugins/betterSessions/index.tsx
Rare case of Discord actually making helpful changes
=> doomsday fix: BetterSessions

src/plugins/reviewDB/components/ReviewComponent.tsx, src/plugins/reviewDB/components/ReviewsView.tsx, src/plugins/seeSummaries/index.tsx
=> doomsday fix: ReviewDB and Summaries

src/plugins/usrbg/index.tsx
(also removed some obsolete stuff)
=> doomsday fix: USRBG

src/plugins/voiceMessages/DesktopRecorder.tsx, src/plugins/voiceMessages/WebRecorder.tsx, src/plugins/voiceMessages/utils.ts
Use currently selected input device instead of the default one.
#2477
=> VoiceMessages: properly respect user's microphone choice

src/plugins/moreKaomoji/index.ts
Fixes missing space between message and Kaomoji
=> fix missing space in MoreKaomoji

src/plugins/mentionAvatars/README.md, src/plugins/mentionAvatars/index.tsx, src/plugins/mentionAvatars/styles.css, src/plugins/roleColorEverywhere/index.tsx, src/plugins/showHiddenThings/index.ts, src/plugins/viewIcons/index.tsx
Shows user avatars inside mentions
=> new plugin MentionAvatars: Shows user avatars inside mentions

src/plugins/betterFolders/index.tsx
=> fix(BetterFolders): Close folders when switching accounts

src/plugins/messageLogger/index.tsx, src/plugins/viewRaw/index.tsx
Fixes https://github.com/Vencord/plugin-requests/issues/975
Read commit description for extra yapping
=> fix: Add ViewRaw & MessageLogger context menu options on threads

src/plugins/pictureInPicture/index.tsx, src/utils/constants.ts
discord added an extra parameter the children array and broke this 😕 here's a fix for that. readded myself as the dev as well, for good this time i swear
=> fix PictureInPicture

src/plugins/superReactionTweaks/index.ts
Added a `0` option to the slider, and a check that returns `false` if the limit is `0`.
=> feat(superReactionTweaks): Allow disabling super reactions

src/plugins/_core/noTrack.ts
I fixed the patch :)
(another small change from me as usual)
=> feat(NoTrack): Fix Patch

src/plugins/openInApp/index.ts, src/utils/constants.ts
tested with https://open.spotify.com/prerelease/1ONe8er39d0DBbwPx6zQjF
=> OpenInApp: support Spotify prerelease links

src/plugins/clearURLs/defaultRules.ts
=> clearURLs: Add si@soundcloud.com to rule list

src/plugins/consoleJanitor/index.ts
https://github.com/Vendicated/Vencord/pull/2892
=> ConsoleJannie: add all discord loggers w/ a whitelist

src/plugins/betterFolders/index.tsx
the old patch matched two things, the new one only matches one
=> BetterFolders: fix patch

src/plugins/volumeBooster/index.ts
fixes https://github.com/Vencord/Vesktop/issues/867 for web, userscript, and vesktop
=> VolumeBooster: fix stream on web based clients

src/plugins/noBlockedMessages/index.ts
closes: https://github.com/Vendicated/Vencord/issues/2920
=> NoBlockedMessage: fix conflicts with message logger

browser/userscript.meta.js
=> Add icon to userscript meta

src/plugins/mutualGroupDMs/index.tsx
*making a seprate pr because the other one might take a while and this was an easy fix*
=> fix MutualGroupDMs

src/plugins/_core/settings.tsx, src/plugins/_core/supportHelper.tsx, src/plugins/arRPC.web/index.tsx, src/plugins/webKeybinds.web/index.ts, src/utils/constants.ts
I'm telling you, I was really cooking with this one. Some might even call this THE best Vencord update.
=> ArmCord -> Legcord

src/plugins/imageZoom/index.tsx
=> fix imageZoom

src/plugins/noPendingCount/index.ts
=> fix noPendingCount

src/plugins/messageLogger/index.tsx, src/plugins/noBlockedMessages/index.ts
plus it's not dependent on lang anymore
=> fix no blocked messages for new i18n system

src/plugins/fakeNitro/index.tsx, src/utils/discord.tsx
discord seems to have pushed this to stable and canary
<https://github.com/Vendicated/Vencord/pull/3003>
=> FakeNitro: Fix embedding animated emojis

src/plugins/viewIcons/index.tsx
the new patch here is kinda cursed, couldnt come up with a better way to do it
=> ViewIcons: Fix conflict with unread Group DMs

src/plugins/pictureInPicture/index.tsx
thank you discord experiment https://discord.com/channels/1015060230222131221/1105582084237570088/1306360174151335979
=> PictureInPicture: Fix button not showing up

src/plugins/viewRaw/index.tsx, src/utils/constants.ts
=> ViewRaw: Add support for Group DMs

src/plugins/consoleJanitor/index.ts, src/webpack/common/utils.ts
might add more fixes to this if I get to them
=> Decor: Fix avatar decorations not showing (again)

src/plugins/clientTheme/index.tsx, src/utils/constants.ts
I no longer desire to associate with the client modding space.
=> Remove no-longer desired collaborator

src/plugins/roleColorEverywhere/index.tsx
Really small change that changes this
to this
=> RoleColorEverywhere: Fix message headers colors

src/plugins/appleMusic.desktop/native.ts
took me way too long to find out what the problem is... apple updated the website and broke the regex somehow
=> fix(appleMusic): token fetching regex broke :(

src/plugins/noUnblockToJump/README.md, src/plugins/noUnblockToJump/index.ts
=> NoUnblockToJump: Also allow jump for ignored users

src/plugins/pictureInPicture/index.tsx
=> PictureInPicture: Fix picture in picture button

src/plugins/_api/chatButtons.ts, src/plugins/betterFolders/index.tsx, src/plugins/betterSettings/index.tsx, src/plugins/consoleJanitor/index.ts, src/plugins/iLoveSpam/index.ts, src/plugins/showTimeoutDuration/index.tsx, src/plugins/viewIcons/index.tsx
will push more later, just better folders for now
=> Fix: Mangled madness

src/plugins/mentionAvatars/index.tsx, src/plugins/openInApp/index.ts, src/plugins/permissionFreeWill/index.ts, src/plugins/showHiddenChannels/index.tsx
just openinapp for now, pushing more as I go
=> fix openinapp

src/plugins/ignoreActivities/index.tsx
should be compatable with stable (havent checked yet)
=> fix ingoreActivities

src/plugins/arRPC.web/index.tsx
This fix works on both stable and canary
=> arRPC: Fix find

src/utils/settingsSync.ts, src/webpack/common/utils.ts
Discord changed the toast types from enum to strings
=> fix ToastType enum

.github/workflows/reportBrokenPlugins.yml, .gitignore, scripts/build/common.mjs, scripts/generateReport.ts, src/Vencord.ts, src/api/Settings.ts, src/debug/Tracer.ts, src/debug/loadLazyChunks.ts, src/debug/runReporter.ts, src/globals.d.ts, src/plugins/_core/noTrack.ts, src/plugins/betterFolders/index.tsx, src/plugins/consoleShortcuts/index.ts, src/plugins/devCompanion.dev/index.tsx, src/plugins/index.ts, src/utils/Logger.ts, src/utils/constants.ts, src/utils/misc.ts, src/utils/patches.ts, src/utils/types.ts, src/webpack/common/menu.ts, src/webpack/index.ts, src/webpack/patchWebpack.ts, src/webpack/webpack.ts, src/webpack/wreq.d.ts
compatible with stable and canary
=> BetterFolders: Fix not disabling expanded folder background

src/plugins/friendInvites/index.ts, src/utils/constants.ts
Fix the plugin (it didn't work)
=> FriendInvites: fix not working in dms

src/debug/runReporter.ts, src/plugins/_core/settings.tsx, src/webpack/common/utils.ts, src/webpack/patchWebpack.ts, src/webpack/webpack.ts
TODO: fix i18n webpack finding
=> fix issues & crashes caused by recent Discord changes

src/api/Notifications/styles.css
=> fix notification background on new ui

src/components/Switch.tsx, src/plugins/consoleShortcuts/index.ts, src/plugins/gameActivityToggle/index.tsx, src/plugins/gameActivityToggle/style.css, src/plugins/typingTweaks/index.tsx, src/plugins/typingTweaks/style.css
- GameActivities (minor style update)
- TypingTweaks (broke in new UI)
- ???
=> Visual refresh fixes

src/plugins/betterFolders/index.tsx, src/plugins/betterFolders/sidebarFix.css
=> BetterFolders: Fix folder bottom margin in main sidebar

src/plugins/vcNarrator/VoiceSetting.tsx, src/plugins/vcNarrator/index.tsx, src/plugins/vcNarrator/settings.ts
Need people to test this on Windows & Mac and let me know if it works fine
=> VcNarrator: Fix Voice selection setting

src/plugins/accountPanelServerProfile/index.tsx, src/plugins/banger/index.ts, src/plugins/roleColorEverywhere/index.tsx
fixes patches for accountpanelserverprofile, rce and banger. only banger is on stable right now.
=> Fix: RCE and others

src/components/VencordSettings/PatchHelperTab.tsx, src/plugins/_api/memberListDecorators/index.tsx, src/plugins/betterRoleContext/index.tsx, src/plugins/betterRoleDot/index.ts, src/plugins/copyUserURLs/index.tsx, src/plugins/decor/ui/components/DecorationContextMenu.tsx, src/plugins/ircColors/index.ts, src/plugins/permissionsViewer/components/RolesAndUsersPermissions.tsx, src/plugins/shikiCodeblocks.desktop/components/ButtonRow.tsx, src/plugins/shikiCodeblocks.desktop/hooks/useCopyCooldown.ts, src/plugins/shikiCodeblocks.desktop/previewExample.tsx, src/plugins/webContextMenus.web/index.ts, src/utils/clipboard.ts, src/utils/index.ts, src/utils/misc.ts, src/webpack/common/utils.ts
The fix for IrcColors could be made in a way where it doesn't match the exact value; however, I don't think it will change.
=> Fix clipboard api, IrcColors, and MemberListDecoratorsAPI

src/plugins/betterFolders/FolderSideBar.tsx, src/plugins/betterFolders/index.tsx, src/plugins/betterFolders/sidebarFix.css
Fix hang on switching to a server that is not currently visible in the sidebar.
=> BetterFolders: Fix freezing the client

scripts/build/build.mjs, scripts/build/buildWeb.mjs, src/webpack/patchWebpack.ts, src/webpack/webpack.ts
Without this the jump to source button just does nothing
=> Fix jumping to patched module sources in new React Dev Tools

src/plugins/noUnblockToJump/README.md, src/plugins/noUnblockToJump/index.ts
it also covers these, but does not state it does in the description
=> NoUnblockToJump: Fix outdated plugin description

src/plugins/mutualGroupDMs/index.tsx
Reflects the way discord does it.
=> Fix MutualGroupDMs members label

src/plugins/accountPanelServerProfile/index.tsx
i think the added patch isn't _great_, open to feedback
=> AccountPanelServerProfile: fix patch

src/components/settings/tabs/plugins/index.tsx, src/webpack/common/components.ts
Fixes the Select and SearchableSelect patches
`className={InputStyles.input}` was removed as it seems to be fine without it from my testing below is with it
=> fix(components): Select Components

src/plugins/memberCount/CircleIcon.tsx, src/plugins/memberCount/MemberCount.tsx, src/plugins/memberCount/index.tsx, src/plugins/memberCount/style.css
Use a circle svg instead of css for the dots
=> feat(MemberCount): Use Circle SVG instead of CSS

src/plugins/arRPC.web/index.tsx
=> arRPC: increase connection timeout to 5s
