src/plugins/experiments.ts
This patches the canUseOverrides variable to re-enable experiments on newer builds.
=> fix(experiments): Patch canUseOverrides variable

src/plugins/nitroBypass.ts
IE, `test:emoji:` turns into `test https://discord[blahblahbla]`, but `test :emoji:` becomes   
`test https://discord[blahblah]` and *not* `test  https://discord[blah]` (which was the prior behaviour)
=> Make NitroBypass only add spaces when there are none

src/plugins/nitroBypass.ts
it was broken by one of the latest discord updates which renamed some functions related to nitro
=> fix(plugin): fix stream quality bypass in nitroBypass

package.json, src/plugins/pronoundb/PronounComponent.tsx, src/plugins/pronoundb/index.ts, src/plugins/pronoundb/types.ts, src/plugins/pronoundb/utils.ts, src/utils/misc.tsx
Uses bulk requests to request all queued users every 300ms (can be changed), and caches all fetched pronouns (even if the request fails, it will not try to fetch it again)
This uses capitalized pronouns (`They/Them` as opposed to `they/them`) right now, but that can be changed
Also updated pnpm because it was being annoying about it
=> Add pronoundb plugin

src/components/PluginSettings/index.tsx
At the moment, all plugins that need the required plugins are shown, instead of only the enabled plugins.
=> show only the required plugins that are enabled

src/plugins/sendify.ts, src/utils/constants.ts
Adds `/track`, `/album`, and `/artist` commands to send song info to your current channel.
=> feat: add sendify plugin

src/components/PluginSettings/PluginModal.tsx, src/utils/types.ts
This PR adds support for a `beforeSave` method that accepts synchronous and asynchronous functions. If `beforeSave` returns true, then the plugin will save & close the modal. If it returns a string, it will display this string to the user and not save.
=> feat(settings): add beforeSave check

src/plugins/experiments.tsx, src/plugins/forceOwnerCrown.ts, src/utils/constants.ts
Fix the plugin spamming errors in console when checking group chats, instead, log them as debugging for people to see if they want to enable verbose console logs.
=> fix forceOwnerCrown Plugin Spamming Errors in Console

src/components/Link.tsx, src/plugins/spotifyControls/PlayerComponent.tsx, src/plugins/spotifyControls/styles.css
It previously opened https://open.spotify.com/artist/null and https://open.spotify.com/track/null
=> spotifyControls: make title/artists of local tracks unclickable

src/plugins/spotifyControls/PlayerComponent.tsx
clicking album of local track will open https://open.spotify.com/album/null. this pr fixes it.
=> spotifyControls: make album of local tracks unclickable

src/plugins/platformIndicators.tsx
Adds the option to only show status in badges, rather than in member list.
=> feat(plugins): Better PlatformIndicator settings

src/plugins/shikiCodeblocks/components/Code.tsx
hljs wasnt working as a fallback because the `highlight.js` package does this:
```ts
declare const hljs : HLJSApi;
```
: D : DD: DD: D: D
maybe we *should* use a separate type-only package..
=> fix: hljs fallback

src/plugins/memberCount.tsx
a lot easier to read the member count, especially in large servers!
before
after
=> add commas in member count

src/components/PluginSettings/PluginModal.tsx, src/plugins/shikiCodeblocks/components/Highlighter.tsx, src/plugins/shikiCodeblocks/hooks/useShikiSettings.ts, src/plugins/shikiCodeblocks/index.ts, src/plugins/shikiCodeblocks/previewExample.tsx, src/utils/types.ts
This modifies the `PluginModal` component to pass down an optional `tempSettings` prop to `settingsAboutComponent`.
The prop works because each setting will create a new object onChange
=> feat(ShikiCodeblocks): Settings preview

src/plugins/showHiddenChannels.tsx
resolves #415
I first modified it to not change the channel type inside the switch
```ts
{
// This is where the logic that chooses the icon is, we override it to be locked if it's hidden
find: ".rulesChannelId))",
replacement: {
match: /(\w+)\.locked(.*?)switch\((\w+)\.type\)/g,
replace: "Vencord.Plugins.plugins.ShowHiddenChannels.isHiddenChannel($3)||$1.locked$2switch($3.type)"
}
},
```
but then noticed it already looks good without that patch, opinions?
=> fix(showHiddenChannels): remove obsolete icons patch

src/plugins/emoteCloner.tsx
Emojis with duplicate names are locally called `emojiName~n`. The `~` is invalid in emoji names and causes the cloner to break.
=> fix: emojis with duplicate names failing to clone

src/plugins/showHiddenChannels.tsx
adds two patches so <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Up</kbd>/<kbd>Down</kbd> and <kbd>Alt</kbd>+<kbd>Up</kbd>/<kbd>Down</kbd> don't teleport you to the void accidentally
=> feat(ShowHiddenChannels): fix channel switch keybinds jumping to hiddens

src/utils/proxyLazy.ts
so you can do the following things
```ts
const x = findLazy(...)
Object.keys(x)
Object.entries(x)
// maybe others
```
=> make proxies enumerable

src/plugins/colorSighted.ts, src/utils/constants.ts
#500, ~~removes~~ changes all of the SVG masks for statuses so that they look like standard colors (aka the online mask) (except for typing and mobile indicators)
=> feat(plugin): ColorSighted

src/plugins/roleColorEverywhere.tsx, src/utils/constants.ts
supersedes #273
colors chat mentions (including in slate), member list role titles, and voice users. typing colors are handled by TypingTweaks so it's not included here to prevent duplicate functionality.
=> feat(plugin): RoleColorEverywhere

src/plugins/revealAllSpoilers.ts, src/plugins/vcDoubleClick.ts
~~Currently, that's the only `onClick` in that module. I could add back the `className: "channelMention"` check if so desired.~~
See second commit
=> fix: vcDoubleClick and revealAllSpoilers patch

src/plugins/customRPC.tsx, src/plugins/lastfm.tsx, src/utils/guards.ts, src/utils/types.ts
this adds real typings for settings definitions that dont have a `default` field:
- `COMPONENT` types are still always `any`
- `SELECT` types are `T | undefined` if there are no `{ default: boolean }` elements
- everything else is `T | undefined` if there is no default field
=> typings for defaultless settings

src/plugins/noDevtoolsWarning.ts
Extends the description of the NoDevtoolsWarning plugin to also document a side effect
=> chore: extend description of NoDevtoolsWarning plugin

src/plugins/FixInbox.tsx
By default, when you open the Unread tab in the Inbox, discord spams a ton of GUILD_SUBSCRIPTIONS events to the gateway. If you're in a lot of servers, this can cause the gateway client to get ratelimited, leaving your client in an unfortunate crash-loop as the gateway attempts to reconnect but just gets ratelimited every time, until you CTRL+R or restart the client.
This plugin stops the client from emitting GUILD_SUBSCRIPTIONS events when you open the Unreads tab. This solves the crashes, but means only already-subscribed guilds will be shown. It seems that high-affinity guilds are already subscribed most of the time, so this doesn't really affect UX much. I think it's a good tradeoff compared to crashing your client :trollface:
=> feat(plugins): add FixInbox plugin

src/components/PluginSettings/components/SettingNumericComponent.tsx, src/components/PluginSettings/components/SettingSelectComponent.tsx, src/components/PluginSettings/components/SettingTextComponent.tsx
This PR fixes setting component input validation and error handling.
When input validation marks an input as an error in numeric, select and text settings fields, the error state is never cleared and so the settings modal can no longer be saved.
When a numeric settings field is invalid, the previous behavior of throwing away the invalid input makes editing the field awkward and unpleasant.  This PR improves that by allowing invalid values to be set but the form cannot be saved until the error is corrected.
=> fix: settings input validation and error handling

src/plugins/roleColorEverywhere.tsx
Adds null checks for both channel and guild ID, and short circuits both of them being undefined when getting a color.
Fixes #646.
=> fix(RoleColorEverywhere): MessageLinkEmbeds DM error

src/plugins/messageLogger/deleteStyleText.css, src/plugins/messageLogger/messageLogger.css
hello! little pr that adds more styles to elements inside deleted messages:
- shows links in darker red (with underline to see they're links), instead of plain blue
- applies grayscale filter to iframes too (for example, spotify embeds)
=> fix messagelogger deleted styles

src/plugins/messageLogger/index.tsx
If it wasn't obvious, these buttons remove the edit history and fully remove deleted messages
=> MessageLogger: Add context menu entry to remove history

src/plugins/index.ts
Adds an extra check into the plugin loader to fix a logic error where API plugins were force enabled even if their dependents weren't.
=> fix: API plugins being force enabled

src/components/VencordSettings/ThemesTab.tsx, src/components/VencordSettings/settingsStyles.css
Primarily fixes bad themes like Spoticord sending the theme links box to the Naughty Corner:tm: and also moves the inline styles to a dedicated class.
=> fix: no more theme box obliteration

src/plugins/imageZoom/styles.css
man naming things is hard.
basically allows you to close the image when you click the backdrop. before you could only do that if you click top or bottom parts of the backdrop but now you can click any part of the backdrop and it will close it
it fixes this:
https://discord.com/channels/1015060230222131221/1015063227299811479/1094745672944726107
thanks aaaz#0001
=> ImageZoom: Fix not being able to close carousels on sides

src/Vencord.ts, src/utils/settingsSync.ts
Fixes a bug where settings didn't actually import (QuickCSS worked fine) since we were overwriting the settings object after importing.
=> CloudSync: fix accidently applying stale settings (#915

src/plugins/fakeNitro.tsx
Changed the message that'll pop up when clicking on a fake emoji, to be shorter, to make the popup smaller. I also changed it so it doesn't sound like it will only look like actual emojis for Vencord users, instead of anyone any modded Discord using similar plugins.
=> Improve FakeNitro emoji popup message

src/plugins/muteNewGuild.tsx, src/utils/constants.ts
Gives the user the ability to toggle which notification should be suppressed or not.
=> MuteNewGuilds: add toggles for guild, everyone, and roles.

src/components/VencordSettings/ThemesTab.tsx
Adds a `<strong>` tag around the reminder to use raw links for themes.
Should be at least a little helpful to users that tend to gloss over small text.
Preview:
=> style(Settings): Make the text about raw theme links bold

src/plugins/usrbg/index.tsx
The reason for doing this is that having Nitro's badge doesn't make much sense. There could be another badge but i'm pretty sure it's only intended for a plug in the first place!
=> USRBG: Hide Nitro badge if banner's source is USRBG

src/plugins/noReplyMention.tsx, src/utils/constants.ts
Adds a new behavior option to NoReplyMention that lets you avoid pinging only specific users instead of only not pinging specific users.
Note: Not sure if I was supposed to add myself to the author list or not, looking through commit history it seems like I am.
=> NoReplyMention: add option to only exclude specific users from pings

src/plugins/typingTweaks.tsx
This adds support for Discord's new global display name feature rolled out ahead of the new username system, and makes it prefer the global display name over the username like the stock client does.
=> fix(TypingTweaks): use global displayName over username

src/plugins/noPendingCount.ts, src/utils/constants.ts
This plugin removes the ping count of incoming friend requests, message requests, and nitro offers.
Ping indicators are removed in the following places:
- Home button (count reduced)
- Friends tab button
- Pending tab button
- Message Requests button
- Taskbar icon (count reduced)
The visibility logic of the Message Requests tab button is preserved (i.e. still appears when there are message requests, and disappears otherwise).
=> Plugin: NoPendingCount

src/plugins/pronoundb/index.ts, src/plugins/pronoundb/pronoundbUtils.ts, src/plugins/pronoundb/settings.ts
Limitations: Pronouns are stored in user profiles, not the user obejct. This means that we don't have access to Discord pronouns in chat, only once you open someone's profile
=> PronounDB: Source pronouns from both PronounDB & Discord

src/plugins/imageZoom/components/Magnifier.tsx, src/plugins/imageZoom/index.tsx, src/plugins/imageZoom/styles.css
add nearest neighbour interpolation option.
`image-rendering: pixelated;` demo:
https://googlechrome.github.io/samples/image-rendering-pixelated/index.html
=> ImageZoom: add nearest neighbour

src/plugins/pronoundb/index.ts, src/plugins/pronoundb/pronoundbUtils.ts
We don't need to cache Discord pronouns in the `cache` object, because they're already cached in the user object.
=> PronounDB: fix caching not respecting user preference

src/components/VencordSettings/CloudTab.tsx, src/utils/settingsSync.ts
because otherwise there's no feedback at all when clicking the button
=> fix: send notification when settings are manually synced

src/plugins/messageLogger/index.tsx
Add two new options to outright ignore channels, and guilds from creating
logs with the MessageLogger plugin.
In some high-traffic channels and guilds that receive a lot of edits and/or
deletions (by virtue of so-called "sticky messages"), the MessageLogger
plugin tends to get in the way of reading the chat history.
This patch adds an option to provide a comma-separated list of channel
IDs to ignore from logging. Additionally, after some direct conversation
on the support server, it was concluded to also add an option to ignore
guilds, such that this plugins settings can be considered complete.
(See https://canary.discord.com/channels/1015060230222131221/1015063227299811479/1129443488346419220)
Local tests confirm it is working as intended. To the best of my
knowledge, I followed the …
=> feat(MessageLogger): add option to ignore channels and guilds

src/components/VencordSettings/ThemesTab.tsx
People tend to not find the `open quickcss file` button to add their edited theme file.
cc: toxxy [Ignore]
=> Themes tab: Add QuickCss button

src/plugins/pronoundb/index.ts, src/plugins/pronoundb/pronoundbUtils.ts
It was getting pronouns from the currently focused channel's server if you opened someone's global profile from within a server.
=> fix(PronounDB): don't use guild pronouns in global profile modal

src/plugins/voiceMessages/index.tsx, src/utils/quickCss.ts
The upload button is not supposed to appear in channels in which you can't send messages. However, misconfigured channel permissions (or intentional idk) can make it appear thanks to one perm: create threads. In this case, the "Send voice message" button would still appear, but voice messages can't be sent in that channel. This fixes it.
Note: The third commit undoes the first commit since I suck at git so you can ignore those two
=> VoiceMessages: Improve permission check

src/Vencord.ts
This isn't really a fix per se, more of a heads up to the end user. As more people have started to use Vesktop, people are confused on why Cloud Integrations doesn't work correctly (because the secret doesn't carry over, only their settings, which contains the Cloud Integrations enable state).
The alternative is to move it to IndexedDB, but it would require rewriting a bit of the code whilst I think the temporary bandaid is a good solution until we can get around to redoing it correctly.
=> fix(cloud): cross-client enabling without proper validation

src/plugins/_core/noTrack.ts, src/utils/constants.ts
**NoSentryConsole**: Disables the sentry console log hook to return breadcrumbs to console. Very useful for development and reporting issues alike.
Discord uses Sentry and it will install a hook into the console object.
Doesn't seem that bad, right?
Well, it makes the breadcrumbs/origin in the console from the file that installs that hook,
which ends up making it very hard to tell where non-error logs are coming from!
So this plugin just deletes that hook.
The hook doesn't even do anything anyway, thanks to NoTrack.
This just removes that unnecessary code and allows for a much better experience when debugging,
developing plugins, or reporting issues!
=> feat(plugin): NoSentryConsole

src/plugins/normalizeMessageLinks/index.ts, src/plugins/normalizeResourceLinks/index.ts, src/utils/constants.ts
Finally, I can stop manually removing the `canary.` from my copied links
This patches the copy link button action (which directly reads ambient `location.host`), because any deeper patches would risk breaking functionality.
=> plugins(NormalizeResourceLinks): create plugin

src/plugins/messageLogger/deleteStyleText.css
The bot "thinking" text was previously not shown red when deleted.
I noticed this bug when using YAGPDB's poll feature. When the poll is created, a "YAGPDB.xyz is thinking..." during the creation of the poll, and deleted after. However, it is not shown in red once deleted. Image below.
This PR should fix this bug.
=> messageLogger: apply deleted style to ephemeral messages

src/plugins/clearURLs/defaultRules.ts
Add the new `si` parameter to ClearURLs that has recently been added to sharing modals across YouTube.
Thanks,
pointy
=> ClearURLs: Add si parameter on youtu.be

src/plugins/showTimeouts.ts, src/utils/constants.ts
Shows the timeout chat badge without moderate member perms.
=> feat(plugin): ShowTimeouts

src/plugins/invisibleChat/components/DecryptionModal.tsx, src/plugins/invisibleChat/index.tsx
`secret` is used for both the message with encryption and the message obtained after decrypting -- clarified difference between them in code and modal itself.
also added spacing between the two fields as they were colliding before and didn't look great
(attached: before and after changes)
=> InvisibleChat: fixup decryption modal

src/plugins/lastfm.tsx, src/utils/constants.ts
Adds 2 more options to the lastfm plugin
Artist Only:
Title Only:
=> lastfm: Add setting for artist name and song title only

src/plugins/clearURLs/defaultRules.ts
It removes ?si= from youtube.com/shorts/ links, TESTED, it works.
=> ClearURLs: Add si parameter on youtube.com

src/components/Icons.tsx, src/components/VencordSettings/ThemesTab.tsx, src/plugins/reviewDB/components/MessageButton.tsx, src/plugins/textReplace/index.tsx
This fixes the themes tab on web. The reviewdb icons should look almost the same, in fact maybe slightly better since the viewBox seemed to be different to Discord's (and incorrect?).
=> web: fix themes tab

src/plugins/_api/commands.ts
Fix the command API, broken by discord removing the /giphy command, which was used to locate the injection point for the CommandAPI _init() function. This fix is only a sketchy temporary fix and i am uncertain whether it should be used over a better, more stable solution.. but it works for now for me ig? I am mostly worried that i have seen some users who still have /giphy.. so this would break  the CommandAPI for them..
=> Fix command API

src/plugins/betterNotes/index.tsx, src/plugins/userVoiceShow/components/VoiceChannelSection.css, src/plugins/userVoiceShow/index.tsx
- make betterNotes adds padding when note is hidden and note is last section (so self profile wont missing padding bottom)
because of above change and userVoiceShow is between note box and message box:
- add padding-bottom and remove padding-top of userVoiceShow when in self profile
- remove padding-top because the above change added space above userVoiceShow in self profile even if note is hidden or not
- add padding-bottom because it's now last section, self profile dont have message box below
=> betterNotes, userVoiceShow: fix padding issue

src/plugins/typingIndicator/index.tsx
While this patch (and new ThreeDots find) should work, Vencord's patcher doesn't seem to patch the earliest chunks of Discord, where this patch tries to modify. That will need resolving (and this testing to work more than "Patch OK!") before this can be merged.
=> fix: TypingIndicator

src/plugins/mutualGroupDMs/index.tsx
This fixes a broken patch caused by rspack, as well as an existing bug where the tab would display on your own profile if you had an activity.
=> fix: MutualGroupDMs

src/Vencord.ts
Unrelated sidenote: Fixing shit would be easier if OPENING THE INSPECTOR AT ALL DIDN'T CRASH THE ENTIRETY OF DISCORD. NICE ONE, DISCORD. (yes I literally tried it on vanilla Canary and it still somehow fucking crashes)
=> Fix titlebar duplication with native Windows titlebar

src/plugins/imageZoom/styles.css, src/plugins/pictureInPicture/index.tsx
- ImageZoom: removed CSS that caused media mosaic to warp all the way to the top
- PiP: fixed a bug that replaced the remove attachment button with the PiP button (even on non-video attachments)
=> fix: ImageZoom + PiP

src/plugins/noMosaic/index.ts
static layout works fine to keep render loading image but it isn't responsive if discord window width is too small
haven't found a way to keep both yet
=> noMosaic: play video inline + optional media layout type

src/plugins/dearrow/index.tsx
Currently the plugin tries to replace thumbnails even when only the original thumbnail is available which fails because the `timestamp` for original thumbnails is `null`. This PR simply adds a check if the timestamp is a non-null value.
Example video where this issue currently occurs for me: https://www.youtube.com/watch?v=I6xwMIUPHss
=> fix(dearrow): don't replace thumbnail if only original available

src/plugins/fakeNitro/index.ts
They renamed `canUseStickersEverywhere` to `canUseCustomStickersEverywhere` apparently
=> FakeNitro: Fix using stickers everywhere

scripts/build/build.mjs, scripts/build/common.mjs, src/VencordNative.ts, src/main/ipcPlugins.ts, src/modules.d.ts, src/plugins/fixSpotifyEmbeds.desktop/native.ts, src/plugins/openInApp/index.ts, src/plugins/openInApp/native.ts, src/plugins/voiceMessages/DesktopRecorder.tsx, src/plugins/voiceMessages/native.ts, src/utils/IpcEvents.ts, src/utils/types.ts
This PR adds the ability for any plugin to easily run native code and register ipc methods
Here's how it looks:
**src/plugins/EpicPlugin/native.ts:**
```ts
import { readFileSync } from "fs";
export function readPasswd() {
return readFileSync("/etc/passwd", "utf-8");
}
```
**src/plugins/EpicPlugin/index.ts:**
```ts
import type { PluginNative } from "@utils/types";
const Native = VencordNative.pluginHelpers.EpicPlugin as PluginNative<typeof import("./native")>;
async function doCoolThing() {
const passwd = await Native.readPasswd();
}
```
=> feat: simple plugin natives

src/main/patchWin32Updater.ts
Because it breaks alternative mod-loaders :trollface:
=> feat: Add Environment variable to disable updater auto-patching

src/plugins/dearrow/index.tsx
0 is falsey and would trigger the check before. The original boolean can be used for this instead.
=> fix(dearrow): support DeArrow thumbnail submissions at 0 seconds

src/plugins/shikiCodeblocks.desktop/index.ts
Discovered bug with `Rust` not being a valid language tag, despite Discords builtin code block markdown accepting it. Most likely affects other language identifiers as well.
=> shikiCodeblocks: added toLowerCase to avoid failed detections due to case

src/plugins/quickMention/index.tsx
Fix the check added in #1746 to make the button show up in direct messages.
One remaining issue is the official Discord DM where the button should not show up but I don't know what's the best way to deal with it. First PR, forgive me if something's wrong :p
=> Fix QuickMention not working in DMs

src/components/VencordSettings/PatchHelperTab.tsx
Diff in patch helper overflows the window when the line is too long
=> fix: patch helper overflow

src/plugins/dearrow/index.tsx
These are used by the extension to keep their case. Since this plugin does no autoformatting, it just needs to delete them. Regex only finds words that start with > (`>word`)
=> fix(dearrow): remove > from DeArrow titles

src/plugins/reactErrorDecoder/index.ts, src/utils/constants.ts
* make use of `$self` (probably didn't before because old?)
* fetch errors for the *current* React version, not a hardcoded one
* add myself to `Devs` (if my changes aren't fit for this, i can remove)
<hr>
i noticed this (and checked if desktop was the same):
given i was already making this PR, i thought i would make a few other small changes too :>
=> ReactErrorDecoder: fix using wrong react version's error map

src/plugins/gameActivityToggle/index.tsx
**Summary of changes**
- Update `GameActivityToggle` icon to match new mute, deafen icons.
- Before:
- After:
**Why this is needed**
- Discord recently updated mute and deafen icons, so they no longer match.
**Fun details**
- The new slashes used in the mute and deafen icons are identical SVG data. Consequently, all 3 slashes can match, whereas previously they were all unique to account for apparent icon sizes.
=> GameActivityToggle icon match other toggles

src/plugins/fakeNitro/index.ts
It seems that `getStickerLink` will occasionally give back a `.png` on a gif sticker, despite the `.png` not even being an APNG. I don't know if this is a discord bug or not, I haven't dug that deep, but it seems like this is the simplest solution.
Apologies if this is poor style, I don't write much TS/JS.
Thanks
Sappho
=> fix issue with non apng gif stickers being uploaded

src/plugins/typingIndicator/index.tsx
This PR allows the user to choose whether or not the plugin's typing indicator appears on the channel sidebar of the currently selected channel.
The default value is `TRUE`, as to maintain the same functionality as previous versions of the plugin.
=> feat(plugin): Additional setting for TypingIndicator

src/Vencord.ts
dsGet returns undefined, not null, when a key is missing, so this check never worked (which I'm now confused about because I tested this...)
=> fix: Vencord_cloudSecret check

src/plugins/urbanDictionary/README.md, src/plugins/urbanDictionary/index.ts
I've noticed that I get irrelevant definitions, so I made these changes:
Before, API gave only 10 results and the plugin chose the first result:
After, API gives the number of results you put in the settings and the plugin chooses the result with the most likes:
P.S:
These changes make a huge difference!
=> Urban Dictionary: Chooses top rated definition & more results.

src/plugins/clearURLs/defaultRules.ts
Added "igsh" to the list, I believe Instagram may have replaced igshid with igsh, so it may not be necessary to have them both, but better safe than sorry.
=> ClearURLs: Add igsh

src/plugins/fixYoutubeEmbeds.desktop/README.md, src/plugins/fixYoutubeEmbeds.desktop/index.ts, src/plugins/fixYoutubeEmbeds.desktop/native.ts, src/utils/constants.ts
Allows embedded youtube videos to be played when they're usually blocked.
I *believe* youtube uses window.location.ancestorOrigins to detect this, and it's unreasonably hard to overwrite it. Instead I just reload the frame which clears ancestorOrigins and shouldn't break randomly if the frontend updates.
=> feat(plugin): FixYoutubeEmbeds - fix UMG blocked embeds

src/plugins/fixYoutubeEmbeds.desktop/native.ts
In my case attribute starts with `http` and querySelector cant find it.
=> Fix multilanguage in fixYoutubeEmbeds

src/plugins/spotifyControls/PlayerComponent.tsx, src/plugins/spotifyControls/index.tsx, src/plugins/spotifyControls/spotifyStyles.css, src/utils/constants.ts
I've added (as an option) the cover of the album/track currently playing to the SpotifyControl plugin player
Preview :
=> SpotifyControls: export album cover as CSS variable for themes

src/plugins/fakeNitro/index.ts, src/plugins/fakeNitro/index.tsx
If you use U+2800 then links will essentially be invisible which imo looks way cleaner. Image below is how it should look with the fix.
=> feat(plugin) FakeNitro: Allow customising hyperlink text

src/plugins/lastfm/index.tsx
Just adds an option in the plugin's settings to toggle the last.fm logo. Not much else to say!
With the logo:
Without the logo:
=> LastfmRichPresence: Add an option to hide the Last.fm logo

src/api/ContextMenu.ts, src/plugins/_api/contextMenu.ts, src/plugins/_core/settings.tsx, src/plugins/biggerStreamPreview/index.tsx, src/plugins/copyUserURLs/index.tsx, src/plugins/emoteCloner/index.tsx, src/plugins/imageZoom/index.tsx, src/plugins/index.ts, src/plugins/messageLogger/index.tsx, src/plugins/permissionsViewer/index.tsx, src/plugins/pinDms/contextMenus.tsx, src/plugins/pinDms/index.tsx, src/plugins/resurrectHome/index.tsx, src/plugins/reverseImageSearch/index.tsx, src/plugins/reviewDB/index.tsx, src/plugins/searchReply/index.tsx, src/plugins/serverProfile/index.tsx, src/plugins/translate/index.tsx, src/plugins/unsuppressEmbeds/index.tsx, src/plugins/vencordToolbox/index.tsx, src/plugins/viewIcons/index.tsx, src/plugins/viewRaw/index.tsx, src/plugins/voiceMessages/index.tsx, src/utils/constants.ts, src/utils/types.ts
Clones the context menu props so that they are not mutated (React doesn't like it when you mutate stuff). This makes it safe to run context menu patches at every rerender, so the thing with returning a closure which is run once is removed.[^useEffect] Additionally, since I had to edit all plugins that use context menu patches, I took the opportunity to add a `contextMenus` key to the plugin definition, and made all plugins use that.
[^useEffect]: if you need things that actually do run once, use `useEffect`.
=> Refactor ContextMenuAPI

src/plugins/decor/index.tsx
Decor currently uses a worker to serve decorations. This worker is getting nearly a million hits a day leading to it costing $20+ a month to run Decor.
Changing the formula back to something static will allow me to use R2's public access features instead.
This formula is compatible with the existing worker.
=> chore(Decor): Change URL formula for cost savings

src/plugins/serverProfile/styles.css
discord doesnt crop the banner server-side, so you can upload a tall image and [cause serverprofile's modal layout to explode.](https://files.catbox.moe/g5w1up.png)
this fixes that by cropping the server banner image in (almost) the same way that discord does
=> fix(ServerProfile): crop banner to prevent overflow

src/plugins/favGifSearch/index.tsx
It's possible to save any arbitrary string of text inside of the favourited gif picker, instead of just URLs. This causes favGifSearch to fail with this error:
```
Uncaught TypeError: Failed to construct 'URL': Invalid URL
at Sb (index.tsx:203:17)
at index.tsx:163:67
at Array.map (<anonymous>)
at index.tsx:162:18
at handleOnChange (29062.2bb468e49a2eee40cded.js:1:2798047)
at Object.eI (2541.b44fafd1acac6bd12301.js:1:797772)
at eU (2541.b44fafd1acac6bd12301.js:1:797926)
at 2541.b44fafd1acac6bd12301.js:1:816235
at re (2541.b44fafd1acac6bd12301.js:1:816334)
at rt (2541.b44fafd1acac6bd12301.js:1:816748)
```
This PR simply provides error handling on the URL resolution code, returning the favourited text as-is on failure.
This is obviously very niche behaviour, but would enable compatibility …
=> favGifSearch: don't error on favourited non-urls

src/plugins/memberCount/MemberCount.tsx
When you select the DMs page in discord MemberCount wont load the count at all due to not having a channel loaded and as such will spam console.
Fix:
Adding the ? let it load the count when in the DMs page and stop console spam from it not being able to load the count because no channel is loaded.
=> MemberCount: Fix error when not in a channel

src/plugins/reviewDB/settings.tsx
Since URL used to have an `/` it would redirect to https://reviewdb.mantikafasi.dev//api/redirect instead.
This fix will help with confusion for the average non-techy Vencord user
=> ReviewDB: Fix website url

src/plugins/messageLinkEmbeds/index.tsx
Kinda awkward when you disable a plugin and it doesn't get disabled, no?
=> fix(MessageLinkEmbeds): Actually disable when disabled

src/plugins/pinDms/data.ts, src/plugins/pinDms/index.tsx
Fixed alt + up/down not working as expected and fixed the channel preview when collapsing a category being incorrect when using the most recent message sort option
Resolves #2322
=> PinDMs: Fix unexpected behaviours when using last message sort

src/plugins/startupTimings/index.tsx, src/utils/lazy.ts
`findByPropsLazy` makes the properties of the lazy object also lazy, but that doesn't work for primitives bc `Reflect.get` can't be run on primitives
Before:
After:
=> Better error for primitives on proxyLazy + fix StartupTimings

src/plugins/emoteCloner/index.tsx, src/utils/constants.ts
This pull request simply improves the quality of stickers so that they get cloned to 2048. 
**Before**:
**After**:
=> EmoteCloner: fix low quality; don't count managed emojis

src/plugins/unlockedAvatarZoom/README.md, src/plugins/unlockedAvatarZoom/index.ts, src/utils/constants.ts
Unlocks and allows you to use custom multipliers for the zoom slider in the Edit Avatar modal as the default 2 is "barely enough"
=> new plugin UnlockedAvatarZoom: allows crop zooming in further

src/plugins/showHiddenThings/README.md, src/plugins/showHiddenThings/index.ts
- Renames the plugin to be more generic
- Also shows invites disabled tooltip now
- Adds settings for everything
=> feat(ShowTimeouts): Also show invites disabled tooltip

src/plugins/fakeNitro/index.tsx
It appears that `emoji.url` no longer exists, breaking fakeNitro. This should fix it.
=> fix(fakeNitro): Use getEmojiURL as emoji.url was removed

src/plugins/messageLogger/index.tsx
This removes the redundant check `$2.message.content !== m.editHistory?.[0]?.content` which checks if the new message content is different from the first item in the editHistory. This is not needed (there is another check `$2.message.content !== m.content`), and results in a bug; the other check should be sufficient.
Fixes #2395.
=> messageLogger: fix niche bug ignoring edits when content is same

src/plugins/usrbg/index.tsx
USRBG has moved storage to a new dedicated platform, allowing better integration and more control over the data that can be made available for plugins to use. This has allowed creation of a new API that has several benefits:
- The API's data is updated immediately upon a user's background being approved
- Data sent over-the-pipe can be reduced, only sending a list of user ids and a small bit of metadata (~800kB instead of the current 1.7MB)
- Dead links are no longer a possibility and do not need to be filtered out of the dataset
=> feat(USRBG): update to new API

src/plugins/showHiddenThings/README.md, src/plugins/showHiddenThings/index.ts
This kinda steps on the toes of the user functionality in PermissionsViewer
=> showHiddenThings: also show ModView & hidden discovery servers

src/plugins/lastfm/index.tsx
Defaults to custom status when album name is not set.
=> LastfmRichPresence: Add option to use album name as status name

src/plugins/themeAttributes/README.md, src/plugins/themeAttributes/index.ts
Very minor change, so we didn't add ourselves to the author field.
We use a modified version of the plugin locally because using IDs is unreliable for our use case (theming PluralKit messages) and having the username exposed makes it possible.
Thought we might as well open up a PR for it rather than let it sit alone in a gist somewhere.
=> ThemeAttributes: add data-author-username to messages

src/plugins/dearrow/index.tsx
Adds two new options to the `Dearrow` plugin.
- Ability to hide the `Dearrow Toggle` Button
- Ability to only replace certain elements
- `Titles`, only replaces titles
- `Thumbnails`, only replaces thumbnails
- `Everything`, replaces everything (default)
---
Preview with each option enabled / disabled:
<details>
<summary>Original</summary>
</details>
<details>
<summary><code>Everything</code></summary>
</details>
<details>
<summary><code>Title</code></summary>
</details>
<details>
<summary><code>Thumbnail</code></summary>
</details>
<details>
<summary><code>Hidden Dearrow Button</code> & <code>Everything</code></summary>
</details>
<details>
<summary>Plugin Settings</summary>
</details>
=> Dearrow: allow configuring which elements get dearrowd

src/plugins/messageLogger/deleteStyleOverlay.css, src/plugins/messageLogger/deleteStyleText.css
Colors now use discord variables for better theme compatibility
=> MessageLogger: use discord variables instead of hardcoded colors

src/plugins/themeAttributes/README.md, src/plugins/themeAttributes/index.ts, src/utils/constants.ts
As was advised in https://github.com/Vendicated/Vencord/pull/1976 I have now made an addition to the ThemeAttributes plugin.
The plugin now adds a CSS variable called --large-avatar-url to the img element in the AvatarStack discord uses for the profile pop-outs. This can be used in themes that want to make the profile picture larger without losing image quality as a consequence.
=> ThemeAttributes: add larger avatar url variables to avatars

src/plugins/crashHandler/index.ts, src/plugins/fakeNitro/index.tsx, src/plugins/petpet/index.ts, src/utils/constants.ts, src/webpack/common/stores.ts, src/webpack/common/types/stores.d.ts, src/webpack/common/utils.ts, src/webpack/webpack.ts
The image option for the PetPet command has not been working for about 5 months now, as noted in the closed #2070 pull request. This finally fixes it so it actually works again. This also includes clearing the slash command draft after you run it, so if you run the slash command again, the previously uploaded file from the previous slash command run will not be there in the upload area. The code to clear draft is placed in more than one area within PetPet's code to make sure the slash command draft is cleared even if the command fails and such. Also made DraftType use webpack common and implemented it into the `fakeNitro` and `crashHandler` plugins. Along with DraftType, I also added UploadModule (which is the thing that allows draft clear to happen) to webpack common to make it easier …
=> Fix: PetPet Plugin's Upload Image Option

src/plugins/index.ts
Fixes #2462 
the issue mentioned above applies to all plugins without a start/stop function defined (like MoreKaomoji)
this occurs because the `stopPlugin` and `startPlugin` functions in plugins/index.ts rely on a stop/start function being defined respectively
so when I disable VcNarrator, p.started will still be true bc VcNarrator doesn't have a stop() function defined
then when i try to enable it again, it'll error bc it thinks it's already started
fix is to move the `p.started = true/false` to after that if statement
this way if start() errored then it'll return early and won't set p.started (so everything else should still work as intended)
=> fix: Plugins without start/stop function failing to stop/start

src/plugins/showTimeoutDuration/index.tsx, src/plugins/showTimeoutDuration/styles.css
The tooltip looked too big and crowded, so I made it simpler
Please do clean up stuff if it is a mess
=> ShowTimeoutDuration: Simplify tooltip style, allow changing style without reload

src/plugins/viewIcons/index.tsx, src/utils/constants.ts, src/webpack/common/utils.ts
Lets you view the icon of group channel icons by adding an entry in the context menu called "View Icon".
=> feat(ViewIcons): Group & User DMs icons support

src/plugins/ReplaceGoogleSearch/index.tsx, src/utils/constants.ts
This plugin implements a patch to replace the "Search with Google" in the context menu when right clicking on a highlighted word. You can this engine with the dropdown menu in the settings which gives you the options Google, Bing, Yahoo, Github, Kagi, Yandex, AOL, Baidu and Wikipedia. Alternatively, you can enable the "Use Custom Search Engine" option in the settings to use an alternate engine.
<details>
<summary><strong>Screenshots</strong></summary>
</details>
=> [Plugin] ReplaceGoogleSearch

src/plugins/showHiddenThings/index.ts
Current patch doesn't always work as there's multiple functions for fetching Algolia results, might be related to an experiment
=> ShowHiddenThings: more effectively explode Algolia filters

src/plugins/messageLogger/deleteStyleText.css
This fixes bug where Markdown headers from deleted logged messages don't show as red text (if option is enabled)
without fix:
with fix:
=> fix(MessageLogger): correctly mark markdown headers red

src/plugins/maskedLinkPaste/README.md, src/plugins/maskedLinkPaste/index.ts, src/utils/constants.ts
Pasting a link while you have text selected will paste your link as a masked link at that location
=> new plugin: MaskedLinkPaste

src/plugins/customRPC/index.tsx
Fixed up the spelling from "milisecond" to "milliseconds" :3
=> customRPC: fix typos in settings descriptions

src/plugins/dearrow/index.tsx
Fixed ">" handling at the start of DeArrow titles. Regex taken straight from https://github.com/ajayyy/DeArrow/blob/669a392c39593984aea19bfdac91b19da467def9/src/titles/titleFormatter.ts#L474
Before:
After:
[test video](https://www.youtube.com/watch?v=egxSBhfjcTU)
=> Dearrow: fix ">" handling

src/plugins/ctrlEnterSend/index.ts
This plugin is broken recently because Discord sneakily changed something. Here is a fix.
It seems that Discord changed the logic for message submission back to what it was before last major update.
=> ctrlEnterSend: fix for new Discord update

src/components/VencordSettings/ThemesTab.tsx, src/components/VencordSettings/settingsStyles.css
The CSS class for textarea is no longer in the main webpack bundle, so this PR just copies over the styles
=> fix Online Themes tab

src/plugins/webKeybinds.web/index.ts
Ctrl+Tab already didn't work, but for some reason it seems you can actually override Ctrl+(Shift)+T (open new tab/reopen last tab)
=> [Webkeybinds] Don't override browser keybinds

src/plugins/pronoundb/index.ts
The text in the tooltip (after patching) is:
```js
d.Z.Messages.USER_PROFILE_PRONOUNS + vcHasPendingPronouns ? "" : ` (${vcPronounSource})`
```
... which ends up checking if `'Pronomsfalse'` is truthy, so the whole thing ends up evaluating to `''`, and we end up with an empty tooltip on the pronouns field in the profile.
Adding parentheses makes sure it's checking `vcHasPendingPronouns` only:
```js
d.Z.Messages.USER_PROFILE_PRONOUNS + (vcHasPendingPronouns ? "" : ` (${vcPronounSource})`)
```
This evaluates to `'Pronoms (Discord)'` as intended.
=> PronounDB: fix pronoun tooltip

src/api/Commands/index.ts, src/api/Commands/types.ts
this fixes a crash caused by vencord commands lacking the `untranslatedName` and `untranslatedDescription` fields by.. adding them
(ty aaamia for finding this bug)
=> fix crashing on canary when searching slash commands

src/plugins/timeBarAllActivities/index.tsx
Discord moved where they keep the activity message text, so here's a fix for the patch.
=> TimeBarAllActivities: Fix patch

src/plugins/betterFolders/README.md, src/plugins/betterFolders/index.tsx
when rendering pending guild applications better folders breaks and will not let you see them, this fixes that
=> Fix: BetterFolders rendering pending guild applications

src/plugins/appleMusic.desktop/index.tsx, src/plugins/appleMusic.desktop/native.ts
Apple got rid of the old `tools.applemediaservices.com` search endpoint, so now we have to fetch from the API that `music.apple.com` uses with an extracted hardcoded token. Cheers!
=> AppleMusicRichPresence: fix metadata fetching

src/plugins/replaceGoogleSearch/index.tsx
Without the `?q=`, some searches will go to the wrong place such as the download for DuckDuckGo if you put anything that starts with `x`.
=> fix(ReplaceGoogleSearch): DuckDuckGo URL

src/plugins/roleColorEverywhere/index.tsx
Adapted from my [ColorMessage](<https://github.com/Kyuuhachi/VencordPlugins/tree/main/ColorMessage>) plugin.
=> feat(RCE): Add a touch of color to message contents

src/plugins/fakeNitro/index.tsx
the intentions for `STATUS` seem to be the same as `CHAT`, and fake nitro doesn't patch `STATUS`
closes: https://github.com/Vendicated/Vencord/issues/2897
=> FakeNitro: fix voice calls showing the patched menu

src/plugins/roleColorEverywhere/index.tsx
because of the `settings.use` in `useMessageColor`, a restart is not actually needed for the setting to apply
=> chore(RCE): drop restartneeded from message sat

src/plugins/showHiddenChannels/index.tsx
This fixes a bug in show hidden channels where you could not move things down if they **were not** in a category.
You also could not move uncategorized channels up or down.
This bug was caused by the `Uncategorized` category being filtered out, breaking discords code.
=> Fix: Moving channels (read desc.)

src/plugins/decor/ui/modals/CreateDecorationModal.tsx
had a few people upset about getting banned (or getting upset on someone elses behalf) over resubmitting decors that were rejected because they didn't receive the dm, this should make it clearer that should be in the server and enable dms there if dms arent allowed globally
=> Decor: Update notice about joining the server for clarity

src/api/ChatButtons.tsx
This adds support for the [auxclick event](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event) which triggers when any non-primary mouse button is pressed. This means it will allow for detecting middle clicks on chat bar buttons, although it will *also* trigger for right clicks but that can be avoided by checking the event button when utilizing the auxclick event.
=> Add support for onAuxClick on ChatBarButton

src/plugins/showHiddenThings/index.ts
Mod view has a lot of useful information in one place. there have been several time where I have wanted to open it on myself, but have not been able to. This fixes that. 
I'm not sure if this should be hidden behind the Show Mod View setting, but it made the most sense to me.
=> ShowHiddenThings: Allow opening mod view on yourself

src/api/Commands/index.ts
If you omit options from a subcommand as you are allowed to do, the options argument will be filled in with the parent's options creating a recursive loop ending in `RangeError: Maximum call stack size exceeded`. This resets the options to `undefined` if they were intentionally left out.
=> CommandsAPI: Fix spread overwriting omitted subcommand options

src/plugins/typingTweaks/index.tsx
not sure if this was introduced by https://github.com/Vendicated/Vencord/commit/9d3c91e9df7f5168da2ce8b6d1f60e0fd792f935
or if it came from one of discords changes
=> TypingTweaks: Fix usernames not being colored

src/plugins/quickReply/index.ts
Fixes Vendicated/Vencord#3085
Additionally this refactors flux listeners to new standard and tries to replicate stock reply button behaviour slightly more accurately
=> QuickReply: Prevent caret from moving when selecting message

src/plugins/openInApp/index.ts
There's a form of Apple Music link that starts with `geo`, you can commonly get these from link websites from songs and such. 
As a result I noticed that they currently don't open in Apple Music, like the rest of the regular share links. 
All this PR does is add an optional `geo.` part to the regex match.
=> OpenInApp: Add support for geo.music.apple.com links

src/plugins/spotifyControls/PlayerComponent.tsx, src/plugins/spotifyControls/index.tsx
This makes spotifycontrols behave like every sane media player in history.
If the setting is enabled, and playtime is above 3 seconds, using the previous button will restart the currently playing song instead of going to the previous one
=> SpotifyControls: Setting to restart playing song if playtime >3s

src/plugins/consoleShortcuts/index.ts, src/utils/modal.tsx
they're useful for adding breakpoints to find out where a modal is
opened from, and annoying to find
=> ConsoleShortcuts: Add openModal and openModalLazy

src/plugins/consoleShortcuts/index.ts
=> ConsoleShortcuts: Patch Symbol.toStringTag on FluxStore to be the store name

src/plugins/revealAllSpoilers/index.ts
there are two classes for messagesWrapper now, and the second one doesnt
match anything with querySelector
=> RevealAllSpoilers: Fix error on <C-S-Click>

src/components/PluginSettings/PluginModal.tsx, src/plugins/ignoreActivities/index.tsx, src/plugins/index.ts, src/plugins/messageTags/index.ts, src/plugins/pinDms/components/CreateCategoryModal.tsx, src/plugins/pinDms/components/contextMenu.tsx, src/plugins/pinDms/data.ts, src/plugins/pinDms/index.tsx, src/plugins/textReplace/index.tsx, src/shared/SettingsStore.ts, src/utils/types.ts
Adds support for using Array Settings which sync whenever the array is modified, however they currently have no UI implementation and are always hidden.
This should be used for saving data which is handled by its own UI, like PinDMs. The difference of using this from DataStore is that the data gets cloud synced.
=> Implement partial support for Array Settings

eslint.config.mjs, src/components/PluginSettings/PluginModal.tsx, src/plugins/ignoreActivities/index.tsx, src/plugins/index.ts, src/plugins/messageTags/index.ts, src/plugins/pinDms/components/CreateCategoryModal.tsx, src/plugins/pinDms/components/contextMenu.tsx, src/plugins/pinDms/data.ts, src/plugins/pinDms/index.tsx, src/plugins/textReplace/index.tsx, src/shared/SettingsStore.ts, src/utils/types.ts, src/webpack/common/types/components.d.ts
Adds support for using objects/array settings which sync whenever they are modified, however they have no UI implementation and are always hidden.
This should be used for saving data which is handled by its own UI, like PinDMs. The difference of using this from DataStore is that the data gets cloud synced.
=> Settings API: add support for custom objects / arrays

src/shared/SettingsStore.ts
Fix the settings in the Vencord tab not notifying listeners, so switches don't work and changes aren't saved
=> Fix top level settings notifying global listeners

src/plugins/quickReply/index.ts
Yeah turns out this is backwards, currently the code checked if it was in a private channel, which in servers is false, so it never shows up.
This is backwards to discords behaviour, and this change makes the dm toggle appear in servers (and not in dms instead).
=> Reverse dm check condition in QuickReply plugin

eslint.config.mjs, scripts/generateReport.ts, src/debug/loadLazyChunks.ts, src/debug/runReporter.ts, src/plugins/_core/noTrack.ts, src/plugins/index.ts, src/webpack/patchWebpack.ts, src/webpack/webpack.ts, src/webpack/wreq.d.ts, tsconfig.json
Decreases the amount of closures WebpackPatcher creates heavily. Before two closures would be created for every module. One for the getter and one for the wrapper. Now none of those creates closures anymore and instead rely on a single proxy handler
=> WebpackPatcher: Use way less closures

src/plugins/showHiddenChannels/index.tsx
Hidden channels were not displaying as muted when using ShowMode.HiddenIconWithMutedStyle
=> SHC: Fix hidden channels not displaying as muted

src/plugins/consoleJanitor/index.ts, src/plugins/consoleJanitor/index.tsx, src/utils/types.ts, src/webpack/common/components.ts, src/webpack/common/types/components.d.ts
adding this feature because somehow a react error was logged by one of the loggers, and didn't show up anywhere else in the console
=> ConsoleJanitor: Support allowing log levels

src/plugins/emoteCloner/index.tsx, src/webpack/common/utils.ts
=> EmoteCloner: Fix crash with Guild.getMaxEmojiSlots

src/main/index.ts, src/utils/dependencies.ts
UNPKG has not been actively maintained and has been down since `Mar 15, 2025` (https://github.com/unpkg/unpkg/issues/412).
The PR replaces UNPKG usage so that the Monaco Editor and Shiki are loaded from jsDelivr. And since all the UNPKG usages are replaced, the CSP is also changed to `cdn.jsdelivr.net`.
=> Replace UNPKG with jsDelivr

src/plugins/messageLatency/index.tsx
Previously, a delta such as `25199000` would display as 
However, this is just incorrect as it is actually 
The logic on this should be correct now, I tested with a few different values.
=> MessageLatency: Fix off by one error on some deltas

src/plugins/volumeBooster/index.ts
For some reason (please let me know if you know why), setSinkId errors when passed the string "default", despite discords code doing the same thing and not erroring. This can cause errors in the console and audio playback to stop if you swap to the default device after using a non-default device.
an empty string is the same as the default device
=> VolumeBooster: Fix error when going back to the default device

src/api/Commands/index.ts
Discords command list would have missing gaps in the IDs which would cause vencord commands to overlap with some discord commands causing a buggy UI after clicking around in it for a bit.
https://github.com/user-attachments/assets/a1184bcf-c7ad-481c-88db-e6ec75cd73c7
=> CommandsAPI: Fix issue with overlapping IDS

src/components/VencordSettings/VencordTab.tsx
=> chore: change donor card text to include users without a badge

src/plugins/implicitRelationships/README.md, src/plugins/implicitRelationships/index.ts
Discord updated their logic so you no longer need a mutual guild for a user to be considered an implicit relationship. This makes the plugin logic quite a bit simpler (it should now be a lot faster as it loads asynchronously). Unfortunately, it also means some users may not show up in the list if the user object isn't cached, but I don't think it's worth adding HTTP fetching logic for these rare edge cases.
=> fix(ImplicitRelationships): update logic

src/plugins/betterFolders/index.tsx, src/plugins/mutualGroupDMs/index.tsx, src/plugins/plainFolderIcon/index.ts, src/plugins/plainFolderIcon/style.css
Discord now uses css to switch bewteen the plain and mini guild folder icons.
However, the folder icons are transparent and look terrible, so set a sane background color (same as home icon)
=> PlainFolderIcon: Fix plugin not working

src/plugins/showHiddenChannels/index.tsx, src/utils/constants.ts
`Server Guide`, `Channels & Roles`, and `Browse Channels` now correctly show their icons in the chat channel selection bar.
Before:
After:
=> ShowHiddenChannels: Fix showing lock icon for special channels

src/plugins/messageClickActions/index.ts
when holding backspace and alt-tabbing out, the `isDeletePressed` variable stays true, which causes messages to be deleted unintentionally on click.
this bug has happened to me like **30** times on accident and it's annoying. it’s not super frequent, but when it does happen, it’s really frustrating.
this probably impacts a lot of other users. in fact i know it impacts a few of my friends using vencord.
=> MessageClickActions: make delete key detection consistent on lost focus

src/plugins/webScreenShareFixes.web/index.ts
Toggle WebScreenShareFixes stereo streaming params if the audio stream is a screen share
discord itself already does this for the usedtx param hence the easy variable capture :3
=> fix(webScreenShareFixes): toggle stereo params if `sendingVideo`

src/plugins/serverInfo/GuildInfoModal.tsx
Minor correction. The official name is Server Boosts, not Nitro Boosts.
=> ServerInfo: Rename "Nitro Boosts" to "Server Boosts"

src/shared/SettingsStore.ts
Currently any declared `onChange` options on a plugin setting are being fired twice.
=> Prevent onChange setting option from being fired twice.

src/plugins/fakeNitro/index.tsx
haven't tested myself yet, but elvyra says it works fine
=> FakeNitro: fix crash when embed.url is undefined

src/plugins/fakeNitro/index.tsx
This might seem like a little thing, but I personally feel like size 96 is just the perfect size for sending emojis in acceptable quality without them being too big. Size 64 appears rather blurred, but size 128 is just too big in my personal opinion. When using [this](https://github.com/Rico040/bunny-plugins/tree/master/plugins/freemoji) plugin with Revenge I always use size 96, and I think having that in Vencord would be nice as well.
=> Added size 96 for fake nitro emojis

src/debug/loadLazyChunks.ts
The old code stringifies wreq.u to get the export map
But it now is a wrapper function so it doesn't include the object inline anymore
Simple solution is to just use a getter on the `Object.prototype` for a unique symbol, then call the method with that symbol to get the object it's using. Compatible with both the new and old code
=> fix reporter on canary
